'use client';
import {useState} from 'react';
import {ArrowDownUp,Search} from 'lucide-react';
import {progressFor,type TrainerCourse,type WorkRecord} from '@/lib/trainer-domain';
import {Button} from '@/components/ui/button';
export default function CourseDataTable({courses,records,progress}:{courses:TrainerCourse[];records:WorkRecord[];progress?:Record<string,{percent:number|null}>}){
 const[query,setQuery]=useState(''),[sort,setSort]=useState<'name'|'reference'|'trainees'>('name'),[descending,setDescending]=useState(false),[page,setPage]=useState(0);
 const allRows=[...courses].sort((a,b)=>{const comparison=sort==='trainees'?a.trainees-b.trainees:a[sort].localeCompare(b[sort],'ar',{numeric:true});return descending?-comparison:comparison}),rows=allRows.filter(c=>(c.name+' '+c.reference+' '+c.code).includes(query)),pages=Math.max(1,Math.ceil(rows.length/10)),current=Math.min(page,pages-1);
 const visibleKeys=new Set(rows.slice(current*10,current*10+10).map(c=>c.key));
 const completion=(c:TrainerCourse)=>{const value=progress?.[c.key]?.percent??progressFor(records,c.key).percent;return value===null?'غير متاح':value+'٪'};
 function order(key:typeof sort){setSort(key);setDescending(sort===key?!descending:false);setPage(0)}
 return <div className="course-data-table"><div className="table-toolbar"><label><Search size={17}/><input aria-label="البحث في جدول الشعب" placeholder="ابحث باسم المقرر أو الرقم المرجعي" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></label><small>{rows.length} شعبة</small></div><div className="table-scroll" role="region" aria-label="جدول الشعب التدريبية" tabIndex={0}><table className="portfolio-table"><caption className="sr-only">مقررات المدرب وشعبه وأعداد المتدربين وحالاتهم ومؤشر الإنجاز</caption><thead><tr>{([['name','المقرر'],['reference','الرقم المرجعي'],['trainees','المتدربون']] as const).map(([key,label])=><th scope="col" key={key} aria-sort={sort===key?(descending?'descending':'ascending'):'none'}><button aria-label={'ترتيب حسب '+label} onClick={()=>order(key)}>{label}<ArrowDownUp size={13}/></button></th>)}<th>المحرومون</th><th>المنسحبون</th><th>مطوي القيد</th><th>الإنجاز</th></tr></thead><tbody>{allRows.map(c=><tr key={c.key} className={visibleKeys.has(c.key)?undefined:"table-print-row"}><td><b>{c.name}</b><small>{c.code}</small></td><td>{c.reference}</td><td>{c.trainees}</td><td>{c.deprived}</td><td>{c.withdrawn}</td><td>{c.dismissed}</td><td>{completion(c)}</td></tr>)}</tbody></table>{!rows.length&&<p className="empty-state no-print">لا توجد نتائج مطابقة.</p>}</div>{pages>1&&<div className="table-pagination"><Button variant="outline" disabled={current===0} onClick={()=>setPage(current-1)}>السابق</Button><span>صفحة {current+1} من {pages}</span><Button variant="outline" disabled={current+1>=pages} onClick={()=>setPage(current+1)}>التالي</Button></div>}</div>;
}
