'use client';
import {useState} from 'react';
import {ArrowDownUp,Search} from 'lucide-react';
import {progressFor,type TrainerCourse,type WorkRecord} from '@/lib/trainer-domain';
import {Button} from '@/components/ui/button';
export default function CourseDataTable({courses,records}:{courses:TrainerCourse[];records:WorkRecord[]}){
 const[query,setQuery]=useState(''),[sort,setSort]=useState<'name'|'reference'|'trainees'>('name'),[descending,setDescending]=useState(false),[page,setPage]=useState(0);
 const rows=courses.filter(c=>(c.name+' '+c.reference+' '+c.code).includes(query)).sort((a,b)=>{const comparison=sort==='trainees'?a.trainees-b.trainees:a[sort].localeCompare(b[sort],'ar',{numeric:true});return descending?-comparison:comparison}),pages=Math.max(1,Math.ceil(rows.length/10)),current=Math.min(page,pages-1);
 function order(key:typeof sort){setSort(key);setDescending(sort===key?!descending:false);setPage(0)}
 return <div className="course-data-table"><div className="table-toolbar"><label><Search size={17}/><input aria-label="البحث في جدول الشعب" placeholder="ابحث باسم المقرر أو الرقم المرجعي" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></label><small>{rows.length} شعبة</small></div><div className="table-scroll"><table className="portfolio-table"><thead><tr>{([['name','المقرر'],['reference','الرقم المرجعي'],['trainees','المتدربون']] as const).map(([key,label])=><th key={key} aria-sort={sort===key?(descending?'descending':'ascending'):'none'}><button onClick={()=>order(key)}>{label}<ArrowDownUp size={13}/></button></th>)}<th>المحرومون</th><th>المنسحبون</th><th>مطوي القيد</th><th>الإنجاز</th></tr></thead><tbody>{rows.map((c,index)=><tr key={c.key} className={index>=current*10&&index<current*10+10?undefined:"table-print-row"}><td><b>{c.name}</b><small>{c.code}</small></td><td>{c.reference}</td><td>{c.trainees}</td><td>{c.deprived}</td><td>{c.withdrawn}</td><td>{c.dismissed}</td><td>{progressFor(records,c.key).percent??'—'}٪</td></tr>)}</tbody></table>{!rows.length&&<p className="empty-state">لا توجد نتائج مطابقة.</p>}</div>{pages>1&&<div className="table-pagination"><Button variant="outline" disabled={current===0} onClick={()=>setPage(current-1)}>السابق</Button><span>صفحة {current+1} من {pages}</span><Button variant="outline" disabled={current+1>=pages} onClick={()=>setPage(current+1)}>التالي</Button></div>}</div>;
}
