'use client';
import {useEffect,useState,FormEvent} from 'react';
import {Plus,Download,Upload} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';

type Kind='initiative'|'improvement';
type Category='withdrawn'|'dismissed'|'deprived';
type Status='planned'|'in_progress'|'completed';
type Evidence={id:string;original_filename:string;byte_size:number;created_at:number};
type Action={id:string;kind:Kind;category:Category|null;title:string;description:string;expected_result:string;status:Status;target_date:string|null;created_at:number;evidence:Evidence[]};
const categories:Record<Category,string>={withdrawn:'الانسحاب',dismissed:'طي القيد',deprived:'الحرمان بسبب الغياب'};
const statuses:Record<Status,string>={planned:'مخطط لها',in_progress:'قيد التنفيذ',completed:'مكتملة'};
export default function DepartmentActions({csrf}:{csrf:string}){
 const[actions,setActions]=useState<Action[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[editor,setEditor]=useState<Action|{kind:Kind}|null>(null);
 async function refresh(){const r=await fetch('/api/department/actions',{cache:'no-store'});const d=await r.json() as {error?:string;actions?:Action[]};if(!r.ok)throw new Error(d.error||'تعذر تحميل المبادرات والخطط.');setActions(d.actions||[])}
 useEffect(()=>{let live=true;fetch('/api/department/actions',{cache:'no-store'}).then(async r=>{const d=await r.json() as {error?:string;actions?:Action[]};if(!r.ok)throw new Error(d.error||'تعذر تحميل المبادرات والخطط.');if(live)setActions(d.actions||[])}).catch(e=>{if(live)setError((e as Error).message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[]);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editor)return;setBusy(true);setError('');setNotice('');const f=new FormData(event.currentTarget),kind=editor.kind;
  const payload={kind,category:kind==='improvement'?f.get('category'):null,title:f.get('title'),description:f.get('description')||'',expectedResult:f.get('expectedResult')||'',status:f.get('status'),targetDate:f.get('targetDate')||''};
  try{const id='id'in editor?editor.id:null;const r=await fetch('/api/department/actions'+(id?'/'+id:''),{method:id?'PATCH':'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(payload)});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||'تعذر الحفظ.');await refresh();setEditor(null);setNotice(id?'تم تحديث السجل.':'تم إنشاء السجل.')}
  catch(e){setError((e as Error).message)}finally{setBusy(false)}
 }
 async function upload(event:FormEvent<HTMLFormElement>,id:string){event.preventDefault();setBusy(true);setError('');setNotice('');const form=event.currentTarget;try{const r=await fetch('/api/department/actions/'+id+'/evidence',{method:'POST',headers:{'X-CSRF-Token':csrf},body:new FormData(form)});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||'تعذر رفع الشاهد.');form.reset();await refresh();setNotice('تم حفظ الشاهد مع السجل.')}
  catch(e){setError((e as Error).message)}finally{setBusy(false)}
 }
 return <div className="department-actions">{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="success" role="status">{notice}</p>}{(['initiative','improvement'] as Kind[]).map(kind=><section className="panel" key={kind}><div className="panel-title"><div><h3>{kind==='initiative'?'مبادرات القسم':'خطط تحسين حالات المتدربين'}</h3><p>{kind==='initiative'?'سجل مبادرات القسم العامة ومتابعة تنفيذها.':'إجراءات لمعالجة الحالات والفرق بين تقارير الأعداد والتسجيل، مع شواهد التنفيذ.'}</p></div><Button size="sm" onClick={()=>setEditor({kind})}><Plus size={16}/>{kind==='initiative'?'إضافة مبادرة':'إضافة خطة'}</Button></div>{loading?<p className="department-actions-empty">جارٍ تحميل السجلات…</p>:actions.filter(a=>a.kind===kind).length===0?<p className="department-actions-empty">{kind==='initiative'?'لم تُسجَّل مبادرات بعد.':'لم تُسجَّل خطط تحسين بعد.'}</p>:<div className="department-action-list">{actions.filter(a=>a.kind===kind).map(a=><article className="department-action" key={a.id}><div className="department-action-head"><div><h4>{a.title}</h4><p>{a.category?categories[a.category]+' · ':''}{statuses[a.status]}{a.target_date?' · الموعد المستهدف: '+a.target_date:''}</p></div><Button variant="outline" size="sm" onClick={()=>setEditor(a)}>تعديل</Button></div>{a.description&&<p>{a.description}</p>}{a.expected_result&&<p className="department-action-outcome"><b>النتيجة المستهدفة:</b> {a.expected_result}</p>}<div className="department-action-evidence"><b>الشواهد</b>{a.evidence.length?<div>{a.evidence.map(e=><a key={e.id} href={'/api/department/actions/evidence/'+e.id}><Download size={15}/>{e.original_filename}</a>)}</div>:<small>لا توجد شواهد مرفوعة.</small>}<form onSubmit={e=>upload(e,a.id)}><input type="file" name="file" accept=".pdf,.png,.jpg,.jpeg,.webp" aria-label={'شاهد '+a.title} required disabled={busy}/><Button type="submit" variant="outline" size="sm" disabled={busy}><Upload size={15}/>رفع شاهد</Button></form></div></article>)}</div>}</section>)}
 <Dialog open={!!editor} onOpenChange={o=>!o&&setEditor(null)}><DialogContent dir="rtl" className="app-dialog department-action-dialog"><DialogHeader><DialogTitle>{editor?.kind==='initiative'?'مبادرة القسم':'خطة تحسين'}</DialogTitle><DialogDescription>أدخل الإجراء والنتيجة المستهدفة، ثم أرفق شواهد التنفيذ من البطاقة.</DialogDescription></DialogHeader>{editor&&<form key={'id'in editor?editor.id:editor.kind} onSubmit={save}><label htmlFor="action-title">العنوان</label><Input id="action-title" name="title" required minLength={3} maxLength={140} defaultValue={'id'in editor?editor.title:''}/>{editor.kind==='improvement'&&<><label htmlFor="action-category">الحالة المستهدفة</label><select id="action-category" name="category" required defaultValue={'id'in editor?editor.category||'withdrawn':'withdrawn'}>{(Object.keys(categories) as Category[]).map(k=><option value={k} key={k}>{categories[k]}</option>)}</select></>}<label htmlFor="action-description">الإجراء</label><textarea id="action-description" name="description" maxLength={2500} rows={4} defaultValue={'id'in editor?editor.description:''}/><label htmlFor="action-result">النتيجة المستهدفة</label><textarea id="action-result" name="expectedResult" maxLength={1000} rows={2} defaultValue={'id'in editor?editor.expected_result:''}/><label htmlFor="action-status">حالة التنفيذ</label><select id="action-status" name="status" defaultValue={'id'in editor?editor.status:'planned'}>{(Object.keys(statuses) as Status[]).map(k=><option value={k} key={k}>{statuses[k]}</option>)}</select><label htmlFor="action-date">الموعد المستهدف (اختياري)</label><Input id="action-date" name="targetDate" type="date" defaultValue={'id'in editor?editor.target_date||'':''}/><Button type="submit" disabled={busy}>{busy?'جارٍ الحفظ…':'حفظ'}</Button></form>}</DialogContent></Dialog></div>
}

