'use client';
import {useEffect,useRef,useState,FormEvent} from 'react';
import {FileCheck2,Upload,Download,ClipboardCheck,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {User} from '@/lib/contracts';
import {usePagedResource} from './paged-resource';
type Trainer={id:string;display_name:string;username:string};
type History={id:string;version_id:string;version_number:number;original_filename:string;version_at:number;uploader_name:string;review_status:string|null;note:string|null;reviewed_at:number|null;reviewer_name:string|null};
type Item={id:string;trainer_id:string;trainer_name:string;title:string;review_status:'pending'|'passed'|'failed';latest_version_id:string;version_number:number;original_filename:string;uploader_name:string;updated_at:number};
const date=(n:number)=>new Date(n).toLocaleString('ar-SA',{timeZone:'Asia/Riyadh',dateStyle:'medium',timeStyle:'short'});
const status={pending:'بانتظار المراجعة',passed:'مجتاز',failed:'غير مجتاز'};
function EvidenceHistory({id}:{id:string}){const page=usePagedResource<History>('/api/evidence/'+id+'/history','history');return <div className="history-list">{page.loading?<p role="status">جارٍ تحميل سجل الشاهد…</p>:page.error?<p role="alert" className="error">{page.error}<Button variant="outline" onClick={page.reload}>إعادة المحاولة</Button></p>:<>{page.items.map(h=><div key={h.id}><b>النسخة {h.version_number.toLocaleString('ar-SA')}</b><span>{h.original_filename}</span><small>{h.review_status?date(h.reviewed_at!):date(h.version_at)} · {h.review_status?'مراجعة '+h.reviewer_name:'رفع '+h.uploader_name}</small>{h.review_status&&<p>{h.review_status==='passed'?'مجتاز':'غير مجتاز'}{h.note?' · '+h.note:''}</p>}<a href={'/api/evidence/files/'+h.version_id}>تنزيل هذه النسخة</a></div>)}{page.nextCursor&&<Button variant="outline" disabled={page.moreLoading} onClick={page.loadMore}>عرض سجلات أقدم</Button>}</>}</div>}
export default function EvidencePage({user,csrf}:{user:User;csrf:string}){
 const[trainers,setTrainers]=useState<Trainer[]>([]),[target,setTarget]=useState(''),[selected,setSelected]=useState<Item|null>(null),[title,setTitle]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[review,setReview]=useState<Item|null>(null),[reviewStatus,setReviewStatus]=useState<'passed'|'failed'>('passed'),[reviewNote,setReviewNote]=useState(''),[reviewError,setReviewError]=useState(''),[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState(''),[trainerFilter,setTrainerFilter]=useState(''),[historyId,setHistoryId]=useState('');const requestId=useRef(crypto.randomUUID()),fileInput=useRef<HTMLInputElement>(null),uploadPanel=useRef<HTMLElement>(null);
 const isHead=user.role==='head',params=new URLSearchParams({q:query,status:statusFilter,...(trainerFilter?{trainer:trainerFilter}:{})}),page=usePagedResource<Item>('/api/evidence?'+params,'evidence');
 useEffect(()=>{if(!isHead)return;let active=true;fetch('/api/evidence/trainers').then(async r=>{const d=await r.json() as {trainers:Trainer[];error?:string};if(!r.ok)throw new Error(d.error);if(active)setTrainers(d.trainers)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[isHead]);
 function resetUpload(){setSelected(null);setFile(null);setTitle('');requestId.current=crypto.randomUUID();if(fileInput.current)fileInput.current.value=''}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');setMessage('');if(!file){setError('اختر ملف الشاهد.');return}if(isHead&&!selected&&!target){setError('اختر المدرب صاحب الشاهد.');return}setBusy(true);try{const form=new FormData();form.set('file',file);if(!selected){form.set('title',title);if(isHead)form.set('trainer_id',target)}const path=selected?'evidence/'+selected.id+'/versions':'evidence',r=await fetch('/api/'+path,{method:'POST',headers:{'X-CSRF-Token':csrf,'X-Upload-Id':requestId.current},body:form}),d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setMessage(selected?'حُفظت النسخة الجديدة وأصبحت بانتظار المراجعة.':'حُفظ الشاهد وأصبح بانتظار المراجعة.');resetUpload();await page.reload()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function saveReview(){if(!review)return;setBusy(true);setReviewError('');try{const r=await fetch('/api/evidence/'+review.id+'/review',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({status:reviewStatus,note:reviewNote,versionId:review.latest_version_id})}),d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setReview(null);setMessage('حُفظت المراجعة في سجل الشاهد.');setHistoryId('');await page.reload()}catch(e){setReviewError((e as Error).message)}finally{setBusy(false)}}
 return <div className="evidence-workspace"><p className="context-note">هذه الشواهد يراجعها رئيس القسم. مرفقات متطلبات الشعبة تبقى في صفحات التدريب الخاصة بها.</p><div className="evidence-layout"><section ref={uploadPanel} className="panel evidence-upload" tabIndex={-1}><div className="panel-title"><div><h3>{selected?'إضافة نسخة جديدة':isHead?'رفع شاهد لمدرب':'رفع شاهد'}</h3><p>يظهر لصاحب الشاهد ورئيس القسم فقط.</p></div><Upload size={22}/></div><form onSubmit={submit} className="evidence-form">{selected?<div className="selected-evidence"><span className="eyebrow">الشاهد المحدد</span><b>{selected.title}</b><p>المالك: {selected.trainer_name}</p><small>آخر نسخة: {selected.version_number}</small><Button variant="outline" type="button" disabled={busy} onClick={resetUpload}>العودة إلى شاهد جديد</Button></div>:<>{isHead&&<label>المدرب صاحب الشاهد<select value={target} onChange={e=>{setTarget(e.target.value);requestId.current=crypto.randomUUID()}} required><option value="">اختر مدربًا</option>{trainers.map(t=><option key={t.id} value={t.id}>{t.display_name} · {t.username}</option>)}</select></label>}<label htmlFor="evidence-title">عنوان الشاهد</label><Input id="evidence-title" value={title} onChange={e=>{setTitle(e.target.value);requestId.current=crypto.randomUUID()}} required minLength={3} maxLength={120} placeholder="عنوان يوضح محتوى الشاهد"/></>}<label htmlFor="evidence-file">ملف الشاهد</label><Input ref={fileInput} id="evidence-file" type="file" disabled={busy} accept=".pdf,.png,.jpg,.jpeg,.webp" onChange={e=>{setFile(e.target.files?.[0]||null);requestId.current=crypto.randomUUID()}}/><small className="muted">PDF أو PNG أو JPG أو WebP، حتى ١٠ ميغابايت.</small>{file&&<div className="selected-file"><div><b>{file.name}</b><small>{(file.size/1024).toFixed(0)} كيلوبايت</small></div><Button type="button" variant="ghost" aria-label="إزالة الملف المختار" disabled={busy} onClick={()=>{setFile(null);if(fileInput.current)fileInput.current.value=''}}><X size={17}/></Button></div>}{error&&<p role="alert" className="error">{error}</p>}<Button type="submit" disabled={busy||!file}><Upload size={17}/>{busy?'جارٍ الحفظ…':selected?'رفع النسخة الجديدة':'رفع الشاهد'}</Button></form></section>
 <section className="panel evidence-list"><div className="panel-title"><div><h3>{isHead?'شواهد المدربين':'شواهدك ومراجعاتها'}</h3><p>{page.loading?'جارٍ حساب النتائج…':page.error?'عدد النتائج غير متاح':page.total+' نتيجة وفق التصفية الحالية'}</p></div><FileCheck2 size={22}/></div><div className="list-filters"><label><Search size={17}/><input aria-label="البحث بعنوان الشاهد" placeholder="ابحث بعنوان الشاهد" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>حالة المراجعة<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">كل الحالات</option>{Object.entries(status).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{isHead&&<label>المدرب<select value={trainerFilter} onChange={e=>setTrainerFilter(e.target.value)}><option value="">كل المدربين</option>{trainers.map(t=><option key={t.id} value={t.id}>{t.display_name}</option>)}</select></label>}{(query||statusFilter||trainerFilter)&&<Button variant="ghost" onClick={()=>{setQuery('');setStatusFilter('');setTrainerFilter('')}}>مسح التصفية</Button>}</div>
 {page.loading?<p className="evidence-loading" role="status">جارٍ تحميل الشواهد…</p>:page.error?<div className="error" role="alert">{page.error}<Button variant="outline" onClick={page.reload}>إعادة المحاولة</Button></div>:page.items.length===0?<div className="empty-state"><FileCheck2/><h3>{query||statusFilter||trainerFilter?'لا توجد شواهد مطابقة':'لا توجد شواهد مرفوعة بعد'}</h3><p>{query||statusFilter||trainerFilter?'غيّر التصفية أو امسحها لاستعراض الشواهد.':'اختر ملفًا وأضف عنوانه ليظهر هنا.'}</p></div>:<div className="evidence-items">{page.items.map(i=><article className="evidence-item" key={i.id}><div className="evidence-item-top"><div><h3>{i.title}</h3><p>{isHead?i.trainer_name+' · ':''}النسخة {i.version_number} · {date(i.updated_at)}</p></div><span className={'review-tag '+i.review_status}>{status[i.review_status]}</span></div><div className="evidence-item-actions"><a className="download-link" href={'/api/evidence/files/'+i.latest_version_id}><Download size={16}/>تنزيل آخر نسخة</a><Button variant="outline" size="sm" disabled={busy} onClick={()=>{setSelected(i);setTarget(i.trainer_id);setFile(null);requestId.current=crypto.randomUUID();if(fileInput.current)fileInput.current.value='';uploadPanel.current?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});uploadPanel.current?.focus({preventScroll:true})}}>إضافة نسخة</Button>{isHead&&<Button variant="outline" size="sm" onClick={()=>{setReview(i);setReviewStatus('passed');setReviewNote('');setReviewError('')}}><ClipboardCheck size={16}/>مراجعة</Button>}</div><button className="text-button" aria-expanded={historyId===i.id} onClick={()=>setHistoryId(historyId===i.id?'':i.id)}>سجل النسخ والمراجعات</button>{historyId===i.id&&<EvidenceHistory id={i.id}/>}</article>)}</div>}{page.nextCursor&&!page.loading&&<div className="pagination-actions"><span>عُرض {page.items.length} من {page.total}</span><Button variant="outline" disabled={page.moreLoading} onClick={page.loadMore}>{page.moreLoading?'جارٍ التحميل…':'عرض شواهد أخرى'}</Button></div>}</section></div>{message&&<div role="status" className="success">{message}</div>}
 <Dialog open={!!review} onOpenChange={o=>{if(!o&&!busy)setReview(null)}}><DialogContent dir="rtl" className="app-dialog"><DialogHeader><DialogTitle>مراجعة الشاهد</DialogTitle><DialogDescription>{review?.title} · {review?.trainer_name} · النسخة {review?.version_number}</DialogDescription></DialogHeader><label>نتيجة المراجعة<select value={reviewStatus} disabled={busy} onChange={e=>setReviewStatus(e.target.value as 'passed'|'failed')}><option value="passed">مجتاز</option><option value="failed">غير مجتاز</option></select></label><label htmlFor="review-note">ملاحظة (اختيارية)</label><textarea id="review-note" disabled={busy} maxLength={1000} value={reviewNote} onChange={e=>setReviewNote(e.target.value)} rows={4}/>{reviewError&&<p className="error" role="alert">{reviewError}</p>}<Button disabled={busy} onClick={saveReview}>{busy?'جارٍ حفظ المراجعة…':'حفظ المراجعة'}</Button></DialogContent></Dialog></div>;
}
