'use client';
import {useEffect,useState,FormEvent} from 'react';
import {FileCheck2,Upload,RotateCcw,Download,ClipboardCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Empty,EmptyHeader,EmptyMedia,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import type {User} from '@/lib/contracts';

type Trainer={id:string;display_name:string;username:string};
type History={version_id:string;version_number:number;original_filename:string;version_at:number;uploader_name:string;review_status:string|null;note:string|null;reviewed_at:number|null;reviewer_name:string|null};
type Item={id:string;trainer_id:string;trainer_name:string;title:string;review_status:'pending'|'passed'|'failed';latest_version_id:string;version_number:number;original_filename:string;uploader_name:string;updated_at:number;history:History[]};
const date=(n:number)=>new Date(n).toLocaleDateString('ar-SA');
const status={pending:'بانتظار المراجعة',passed:'مجتاز',failed:'غير مجتاز'};

export default function EvidencePage({user,csrf}:{user:User;csrf:string}){
 const[trainers,setTrainers]=useState<Trainer[]>([]),[items,setItems]=useState<Item[]>([]),[target,setTarget]=useState(''),[existing,setExisting]=useState('new'),[title,setTitle]=useState(''),[file,setFile]=useState<File|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[review,setReview]=useState<Item|null>(null),[reviewStatus,setReviewStatus]=useState<'passed'|'failed'>('passed'),[reviewNote,setReviewNote]=useState('');
 const isHead=user.role==='head';
 async function get<T=Record<string,unknown>>(path:string){const r=await fetch('/api/'+path,{cache:'no-store'});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);return d as T}
 async function refresh(){setLoading(true);try{const [list,people]=await Promise.all([get<{evidence:Item[]}>('evidence'),isHead?get<{trainers:Trainer[]}>('evidence/trainers'):Promise.resolve({trainers:[]})]);setItems(list.evidence);setTrainers(people.trainers)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[user.id]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');setMessage('');if(!file){setError('اختر ملف الشاهد.');return}if(isHead&&existing==='new'&&!target){setError('اختر المدرب صاحب الشاهد.');return}setBusy(true);try{const form=new FormData();form.set('file',file);if(existing==='new'){form.set('title',title);if(isHead)form.set('trainer_id',target)}const path=existing==='new'?'evidence':'evidence/'+existing+'/versions';const r=await fetch('/api/'+path,{method:'POST',headers:{'X-CSRF-Token':csrf},body:form});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setMessage(existing==='new'?'تم حفظ الشاهد للمدرب.':'تم حفظ نسخة جديدة من الشاهد، وعادت للمراجعة.');setTitle('');setFile(null);setExisting('new');(event.target as HTMLFormElement).reset();await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function saveReview(){if(!review)return;setBusy(true);setError('');try{const r=await fetch('/api/evidence/'+review.id+'/review',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({status:reviewStatus,note:reviewNote,versionId:review.latest_version_id})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setReview(null);setReviewNote('');setMessage('حُفظت المراجعة في سجل الشاهد.');await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="evidence-layout"><section className="panel evidence-upload"><div className="panel-title"><div><h3>{isHead?'رفع شاهد لمدرب':'رفع شاهد'}</h3><p>يُحفظ الملف داخل المنصة ويظهر لصاحب الشاهد ورئيس القسم فقط.</p></div><Upload size={22}/></div><form onSubmit={submit} className="evidence-form">{isHead&&<><label>المدرب صاحب الشاهد</label><Select dir="rtl" value={target} onValueChange={setTarget} disabled={existing!=='new'}><SelectTrigger aria-label="المدرب صاحب الشاهد"><SelectValue placeholder="اختر مدربًا"/></SelectTrigger><SelectContent>{trainers.map(t=><SelectItem key={t.id} value={t.id}>{t.display_name} · {t.username}</SelectItem>)}</SelectContent></Select></>}<label>نوع العملية</label><Select dir="rtl" value={existing} onValueChange={setExisting}><SelectTrigger aria-label="نوع العملية"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="new">شاهد جديد</SelectItem>{items.filter(i=>!isHead||!target||i.trainer_id===target).map(i=><SelectItem key={i.id} value={i.id}>نسخة جديدة: {i.title} — {i.trainer_name}</SelectItem>)}</SelectContent></Select>{existing==='new'&&<><label htmlFor="evidence-title">عنوان الشاهد</label><Input id="evidence-title" value={title} onChange={e=>setTitle(e.target.value)} required minLength={3} maxLength={120} placeholder="عنوان يوضح محتوى الشاهد"/></>}<label htmlFor="evidence-file">ملف الشاهد</label><Input id="evidence-file" type="file" required accept=".pdf,.png,.jpg,.jpeg,.webp,application/pdf,image/png,image/jpeg,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/><small className="muted">PDF أو صورة PNG/JPG/WebP · الحد الأقصى ١٠ ميغابايت.</small><Button type="submit" disabled={busy||loading}><Upload size={17}/>{busy?'جارٍ الحفظ…':'رفع الشاهد'}</Button></form></section>
 <section className="panel evidence-list"><div className="panel-title"><div><h3>{isHead?'شواهد المدربين':'جميع الشواهد'}</h3><p>سجل الشواهد ونسخها ونتائج مراجعتها.</p></div><FileCheck2 size={22}/></div>{loading?<p className="evidence-loading">جارٍ تحميل الشواهد…</p>:items.length===0?<Empty><EmptyHeader><EmptyMedia variant="icon"><FileCheck2/></EmptyMedia><EmptyTitle>لا توجد شواهد مرفوعة بعد</EmptyTitle><EmptyDescription>ستظهر هنا فور رفع أول شاهد.</EmptyDescription></EmptyHeader></Empty>:<div className="evidence-items">{items.map(i=><article className="evidence-item" key={i.id}><div className="evidence-item-top"><div><h3>{i.title}</h3><p>{isHead?i.trainer_name+' · ':''}رفع النسخة {i.version_number.toLocaleString('ar-SA')} بواسطة {i.uploader_name}</p></div><span className={'review-tag '+i.review_status}>{status[i.review_status]}</span></div><div className="evidence-item-actions"><a className="download-link" href={'/api/evidence/files/'+i.latest_version_id}><Download size={16}/>تنزيل آخر نسخة</a>{isHead&&<Button variant="outline" size="sm" onClick={()=>{setReview(i);setReviewStatus('passed');setReviewNote('')}}><ClipboardCheck size={16}/>مراجعة</Button>}</div><details><summary>سجل النسخ والمراجعات</summary><div className="history-list">{i.history.map((h,index)=><div key={h.version_id+'-'+index}><b>النسخة {h.version_number.toLocaleString('ar-SA')}</b> · {h.original_filename} · {h.uploader_name} · {date(h.version_at)}{h.review_status&&<span> — {h.review_status==='passed'?'مجتاز':'غير مجتاز'} بواسطة {h.reviewer_name} {h.note&&'· '+h.note}</span>}<a href={'/api/evidence/files/'+h.version_id}>تنزيل</a></div>)}</div></details></article>)}</div>}</section>{error&&<div role="alert" className="error">{error}</div>}{message&&<div role="status" className="success">{message}</div>}
 <Dialog open={!!review} onOpenChange={o=>!o&&setReview(null)}><DialogContent dir="rtl" className="app-dialog"><DialogHeader><DialogTitle>مراجعة الشاهد</DialogTitle><DialogDescription>{review?.title} · النسخة {review?.version_number}</DialogDescription></DialogHeader><label>نتيجة المراجعة</label><Select dir="rtl" value={reviewStatus} onValueChange={v=>setReviewStatus(v as 'passed'|'failed')}><SelectTrigger aria-label="نتيجة المراجعة"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="passed">مجتاز</SelectItem><SelectItem value="failed">غير مجتاز</SelectItem></SelectContent></Select><label htmlFor="review-note">ملاحظة (اختيارية)</label><textarea id="review-note" maxLength={1000} value={reviewNote} onChange={e=>setReviewNote(e.target.value)} rows={4}/><Button disabled={busy} onClick={saveReview}>حفظ المراجعة</Button></DialogContent></Dialog></div>
}



