'use client';
import {useState} from 'react';
import {readGradeWorkbook,gradeSuggestions,selectedGrades,type GradeSheet} from '@/lib/grade-workbook';
import {calculateGrades,type GradeInput,type WorkFile} from '@/lib/trainer-domain';
import {Button} from '@/components/ui/button';
export default function GradeImport({term,onSave,files}:{term:string|null;onSave:(file:File,input:GradeInput)=>Promise<void>;files:WorkFile[]}){
 const[file,setFile]=useState<File|null>(null),[sheets,setSheets]=useState<GradeSheet[]>([]),[sheetIndex,setSheetIndex]=useState(0),[header,setHeader]=useState(1),[column,setColumn]=useState(-1),[first,setFirst]=useState(2),[last,setLast]=useState(2),[maximum,setMaximum]=useState(100),[pass,setPass]=useState(60),[sourceTerm,setSourceTerm]=useState<string>(),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 function choose(sheet:GradeSheet,index:number){const v=gradeSuggestions(sheet);setSheetIndex(index);setHeader(v.header);setColumn(v.column);setFirst(v.firstRow);setLast(v.lastRow);setMaximum(v.maximum);setPass(v.maximum*.6);setSourceTerm(v.term);setConfirmed(false)}
 async function read(file:File){setError('');setBusy(true);try{const values=await readGradeWorkbook(file);setFile(file);setSheets(values);choose(values[0],0)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const sheet=sheets[sheetIndex];let stats:ReturnType<typeof calculateGrades>|null=null,problem='';let input:GradeInput|null=null;
 if(sheet){try{const values=selectedGrades(sheet,column,first,last,maximum);input={...values,maximum,passMark:pass,sheet:sheet.name,column:(sheet.rows[header-1]?.[column]||'')+' ['+(column+1)+']',firstRow:first,lastRow:last};stats=calculateGrades(input)}catch(e){problem=(e as Error).message}}
 const mismatch=!!sourceTerm&&!!term&&sourceTerm!==term;
 return <div className="grade-import"><label className="file-button">اختيار ملف الدرجات<input type="file" accept=".xlsx,.csv" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void read(f);e.target.value=''}}/></label>{files.map(f=><button type="button" className="text-button" key={f.id} disabled={busy} onClick={async()=>{setBusy(true);try{const response=await fetch('/api/trainer/workspace/files/'+f.id);if(!response.ok)throw new Error('تعذر تنزيل الملف السابق.');await read(new File([await response.blob()],f.original_filename))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>إعادة تحليل: {f.original_filename}</button>)}
 {file&&sheet&&<div className="grade-preview"><p><b>معاينة قبل الاعتماد</b> · {file.name}</p><div className="form-grid"><label>ورقة العمل<select value={sheetIndex} onChange={e=>choose(sheets[+e.target.value],+e.target.value)}>{sheets.map((s,i)=><option key={i} value={i}>{s.name}</option>)}</select></label><label>صف العناوين<input type="number" min="1" max={sheet.rows.length} value={header} onChange={e=>{setHeader(+e.target.value);setColumn(-1)}}/></label><label>عمود الدرجات<select value={column} onChange={e=>setColumn(+e.target.value)}><option value="-1">اختر عمود الدرجات</option>{Array.from({length:Math.max(...sheet.rows.slice(0,30).map(r=>r?.length||0))},(_,i)=><option key={i} value={i}>{sheet.rows[header-1]?.[i]||'عمود دون عنوان'} · {i+1}</option>)}</select></label><label>أول صف للمتدربين<input type="number" min="1" value={first} onChange={e=>setFirst(+e.target.value)}/></label><label>آخر صف للمتدربين<input type="number" min={first} max={sheet.rows.length} value={last} onChange={e=>setLast(+e.target.value)}/></label><label>الدرجة العظمى<input type="number" min="1" max="100" step="any" value={maximum} onChange={e=>setMaximum(+e.target.value)}/></label><label>درجة النجاح<input type="number" min="0" max={maximum} step="any" value={pass} onChange={e=>setPass(+e.target.value)}/></label></div>
 <p className="help">الخلايا الفارغة وحالات الغياب لا تتحول إلى صفر. اختر صفوف المتدربين فقط، دون المجاميع أو الرسوم التحليلية. تعتمد نتائج الصيغ على آخر حفظ للملف في Excel.</p>{sourceTerm&&<p>رمز الفصل المكتشف في الملف: <b dir="ltr">{sourceTerm}</b></p>}{mismatch&&<label className="warning"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> الفصل في الملف {sourceTerm} مختلف عن الفصل الحالي {term}. أؤكد أن الدرجات تخص الشعبة الحالية رغم هذا الاختلاف.</label>}
 {problem?<p className="error">{problem}</p>:stats&&<><div className="grade-numbers"><span>الدرجات المعتمدة<b>{stats.count}</b></span><span>صفوف مستبعدة<b>{stats.excluded}</b></span><span>المتوسط من {maximum}<b>{stats.average}</b></span><span>نسبة النجاح<b>{stats.passRate}٪</b></span></div><p className="help">أول عشر درجات مختارة: {input?.scores.slice(0,10).join('، ')}</p></>}
 <Button disabled={busy||!input||!!problem||(mismatch&&!confirmed)} onClick={async()=>{if(!file||!input)return;setBusy(true);setError('');try{await onSave(file,input);setFile(null);setSheets([])}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?'جارٍ اعتماد التحليل…':'اعتماد التحليل وحفظه في ملف الإنجاز'}</Button></div>}{error&&<p className="error" role="alert">{error}</p>}</div>;
}
