'use client';
import {useEffect,useRef,useState} from 'react';
import type {Chart} from 'chart.js';
export function IndicatorRing({value,label='الإنجاز العام',small=false}:{value:number|null;label?:string;small?:boolean}){
 const progress=value===null?0:Math.max(0,Math.min(100,value)),color=value===null?'#8E9293':value>=90?'#356E55':value>=70?'#8D6500':'#A31D35';
 return <div className={'indicator-ring '+(small?'small':'')} role="img" aria-label={label+': '+(value===null?'غير متاح':value+'٪')}><svg className="ring-svg" viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="49" fill="none" stroke="#E8EEF2" strokeWidth="8"/><circle cx="60" cy="60" r="49" fill="none" stroke={color} strokeWidth="8" strokeLinecap="round" pathLength="100" strokeDasharray={progress+' 100'} transform="rotate(-90 60 60)"/></svg><div className="radial-value"><b>{value===null?'—':value+'٪'}</b><span>{label}</span></div></div>;
}

type Series={label:string;values:(number|null)[];color?:string};
export function IndicatorChart({labels,series,type='bar',percent=false,horizontal=false,height=260,title}:{labels:string[];series:Series[];type?:'bar'|'line';percent?:boolean;horizontal?:boolean;height?:number;title:string}){
 const canvas=useRef<HTMLCanvasElement>(null),[failed,setFailed]=useState(false),signature=JSON.stringify({labels,series,type,percent,horizontal});
 useEffect(()=>{let disposed=false,chart:Chart|undefined;const element=canvas.current;if(!element)return;const input=JSON.parse(signature) as {labels:string[];series:Series[];type:'bar'|'line';percent:boolean;horizontal:boolean};setFailed(false);void import('./chart-runtime').then(async module=>{await document.fonts.ready;if(disposed)return;chart=new module.Chart(element,{type:input.type,data:{labels:input.labels,datasets:input.series.map((s,i)=>({label:s.label,data:s.values,borderColor:s.color||['#356E7D','#729D74','#334E78'][i%3],backgroundColor:input.type==='bar'?(s.color||['#356E7D','#729D74','#334E78'][i%3]):'#0a908b14',borderRadius:input.type==='bar'?6:0,borderWidth:input.type==='bar'?0:2,barPercentage:.6,maxBarThickness:35,tension:.25,pointRadius:4,fill:false}))},options:{responsive:true,maintainAspectRatio:false,animation:false,indexAxis:input.horizontal?'y':'x',locale:'ar-SA',plugins:{legend:{display:input.series.length>1,rtl:true,labels:{font:{family:'DIN Arabic, Tahoma, sans-serif',size:13},usePointStyle:true}},tooltip:{rtl:true,textDirection:'rtl',titleFont:{family:'DIN Arabic, Tahoma, sans-serif'},bodyFont:{family:'DIN Arabic, Tahoma, sans-serif'},callbacks:{label:context=>context.dataset.label+': '+(input.horizontal?context.parsed.x:context.parsed.y)+(input.percent?'٪':'')}}},scales:{[input.horizontal?'x':'y']:{beginAtZero:true,max:input.percent?100:undefined,grid:{color:'#e8eff0'},ticks:{precision:input.percent?1:0,color:'#4B4D4E',font:{family:'DIN Arabic, Tahoma, sans-serif',size:13}}},[input.horizontal?'y':'x']:{grid:{display:false},ticks:{color:'#4B4D4E',font:{family:'DIN Arabic, Tahoma, sans-serif',size:13},maxRotation:0}}}}})}).catch(error=>{console.error('indicator_chart_failed',error);if(!disposed)setFailed(true)});return()=>{disposed=true;chart?.destroy()}},[signature]);
 return <div className="indicator-chart" style={{height}}><canvas ref={canvas} role="img" aria-label={title}/>{failed&&<p className="help">تعذر عرض الرسم. القيم متاحة في جدول البيانات.</p>}<details className="chart-data"><summary>بيانات الرسم</summary><table><caption>{title}</caption><thead><tr><th>البند</th>{series.map(s=><th key={s.label}>{s.label}</th>)}</tr></thead><tbody>{labels.map((label,i)=><tr key={i}><td>{label}</td>{series.map(s=><td key={s.label}>{s.values[i]===null?'—':s.values[i]}{percent&&s.values[i]!==null?'٪':''}</td>)}</tr>)}</tbody></table></details></div>;
}
