'use client';
import {useEffect,useRef,useState} from 'react';
import type {ApexOptions} from 'apexcharts';
import type {Chart} from 'chart.js';
export function IndicatorRing({value,label='الإنجاز العام',small=false}:{value:number|null;label?:string;small?:boolean}){
 const host=useRef<HTMLDivElement>(null),[ready,setReady]=useState(false);
 const color=value!==null&&value>=90?'#079b7d':value!==null&&value>=70?'#e1a127':'#dc6571';
 useEffect(()=>{let disposed=false,chart:{render:()=>Promise<void>;destroy:()=>void}|undefined;const element=host.current;if(!element)return;void import('apexcharts').then(async module=>{if(disposed)return;const options:ApexOptions={chart:{type:'radialBar',height:small?125:172,width:small?125:172,sparkline:{enabled:true},animations:{enabled:false},fontFamily:'Segoe UI, Tahoma, sans-serif',toolbar:{show:false}},series:[value??0],colors:[color],plotOptions:{radialBar:{startAngle:-135,endAngle:135,hollow:{size:'70%'},track:{background:'#e4eeed',strokeWidth:'100%'},dataLabels:{show:false}}},stroke:{lineCap:'round'},tooltip:{enabled:false}};chart=new module.default(element,options);await chart.render();if(!disposed)setReady(true)}).catch(()=>{if(!disposed)setReady(false)});return()=>{disposed=true;chart?.destroy()}},[value,color,small]);
 return <div className={'indicator-ring '+(small?'small':'')} role="img" aria-label={label+': '+(value===null?'غير متاح':value+'٪')}><div className="radial-chart" ref={host} aria-hidden="true"/><div className="radial-value"><b>{value===null?'—':value+'٪'}</b><span>{label}</span></div>{!ready&&<div className="radial-fallback" style={{borderColor:color}} aria-hidden="true"/>}</div>;
}
type Series={label:string;values:(number|null)[];color?:string};
export function IndicatorChart({labels,series,type='bar',percent=false,horizontal=false,height=260,title}:{labels:string[];series:Series[];type?:'bar'|'line';percent?:boolean;horizontal?:boolean;height?:number;title:string}){
 const canvas=useRef<HTMLCanvasElement>(null),[failed,setFailed]=useState(false),signature=JSON.stringify({labels,series,type,percent,horizontal});
 useEffect(()=>{let disposed=false,chart:Chart|undefined;const element=canvas.current;if(!element)return;const input=JSON.parse(signature) as {labels:string[];series:Series[];type:'bar'|'line';percent:boolean;horizontal:boolean};void import('chart.js/auto').then(module=>{if(disposed)return;chart=new module.default(element,{type:input.type,data:{labels:input.labels,datasets:input.series.map((s,i)=>({label:s.label,data:s.values,borderColor:s.color||['#0a908b','#e0a329','#5f83c2'][i%3],backgroundColor:input.type==='bar'?(s.color||['#0a908b','#e0a329','#5f83c2'][i%3]):'#0a908b14',borderRadius:input.type==='bar'?6:0,borderWidth:input.type==='bar'?0:2,barPercentage:.6,maxBarThickness:35,tension:.25,pointRadius:4,fill:false}))},options:{responsive:true,maintainAspectRatio:false,animation:false,indexAxis:input.horizontal?'y':'x',locale:'ar-SA',plugins:{legend:{display:input.series.length>1,rtl:true,labels:{font:{family:'Segoe UI, Tahoma, sans-serif',size:11},usePointStyle:true}},tooltip:{rtl:true,textDirection:'rtl',titleFont:{family:'Segoe UI, Tahoma, sans-serif'},bodyFont:{family:'Segoe UI, Tahoma, sans-serif'},callbacks:{label:context=>context.dataset.label+': '+(input.horizontal?context.parsed.x:context.parsed.y)+(input.percent?'٪':'')}}},scales:{[input.horizontal?'x':'y']:{beginAtZero:true,max:input.percent?100:undefined,grid:{color:'#e8eff0'},ticks:{precision:input.percent?1:0,color:'#708792',font:{family:'Segoe UI, Tahoma, sans-serif',size:11}}},[input.horizontal?'y':'x']:{grid:{display:false},ticks:{color:'#3d626e',font:{family:'Segoe UI, Tahoma, sans-serif',size:11},maxRotation:0}}}}})}).catch(()=>{if(!disposed)setFailed(true)});return()=>{disposed=true;chart?.destroy()}},[signature]);
 return <div className="indicator-chart" style={{height}}><canvas ref={canvas} role="img" aria-label={title}/>{failed&&<p className="help">تعذر عرض الرسم. القيم متاحة في جدول البيانات.</p>}<details className="chart-data"><summary>بيانات الرسم</summary><table><caption>{title}</caption><thead><tr><th>البند</th>{series.map(s=><th key={s.label}>{s.label}</th>)}</tr></thead><tbody>{labels.map((label,i)=><tr key={i}><td>{label}</td>{series.map(s=><td key={s.label}>{s.values[i]===null?'—':s.values[i]}{percent&&s.values[i]!==null?'٪':''}</td>)}</tr>)}</tbody></table></details></div>;
}
