'use client';
import {useEffect,useState,useRef,lazy,Suspense,FormEvent} from 'react';
import {ShieldCheck,Eye,EyeOff,LayoutDashboard,Users,FileSpreadsheet,FileCheck2,ClipboardList,Lightbulb,UserRound,LogOut,SlidersHorizontal,GraduationCap,BookOpen,Layers,LockKeyhole,Plus,Settings2,Activity,Check,RotateCcw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {SidebarProvider,useSidebar,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Empty,EmptyHeader,EmptyMedia,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Skeleton} from '@/components/ui/skeleton';
import {roleLabels,roles,defaultLayout,User,Role} from '@/lib/contracts';
const EvidencePage=lazy(()=>import('./evidence-page'));
import AccountAvatar from './account-avatar';
const RayatPage=lazy(()=>import('./rayat-page'));
const RayatIndicators=lazy(()=>import('./rayat-indicators'));
const DepartmentActions=lazy(()=>import('./department-actions'));
const TrainerWorkspace=lazy(()=>import('./trainer-workspace'));
const HeadTasks=lazy(()=>import('./head-tasks'));
import type {OfficeHour} from './profile-editor';
const ProfileEditor=lazy(()=>import('./profile-editor'));

type Layout={density:'comfortable'|'compact';hidden:string[]};
type Dashboard={scope:string;metrics:Record<string,number|null>;rayat:({linked?:boolean;term:string|null;normalizedTerm?:string|null;registered:number|null;withdrawn:number|null;dismissed:number|null;deprived:number|null;unregistered:number|null;withUnexcusedAbsence:number|null;allCourseDeprived:number|null;sections:number|null;sectionRegistrations:number|null;remoteSections:number|null;remoteRegistrations:number|null;confirmedRemoteSections:number|null;continuingRegistrations?:number|null;deprivedRegistrations?:number|null;dismissedRegistrations?:number|null;withdrawnRegistrations?:number|null;staff?:number|null;excludedStaff?:number;reconciliation?:{SF01:number|null;SS01:number|null;SO08:number|null;consistent:boolean;available:number};linkage?:{scheduleSections:number;registrationSections:number;linkedSections:number;sameCourseSections:number;absenceSections:number;linkedAbsenceSections:number;absenceCourses:number;statusCourses:number;linkedCourses:number;excludedCourses:string[];missingAbsenceCourses:string[];electricalTrainees:number;electricalDeprived:number;electricalWithUnexcusedAbsence:number;scheduledTrainers:number}|null})|null;layout:Layout;asOf:number};
type Profile={id:string;display_name:string;username:string;office:string;specialty:string;staff_number?:string;office_hours?:OfficeHour[]};
const metrics=[{id:'trainees',title:'المتدربون',personal:'المتدربين',icon:GraduationCap,color:'teal'},{id:'sections',title:'الشعب التدريبية',personal:'الشعب التدريبية',icon:Layers,color:'blue'},{id:'courses',title:'المقررات',personal:'المقررات',icon:BookOpen,color:'violet'},{id:'trainers',title:'المدربون',personal:'المدربون',icon:Users,color:'amber'}];
const paths:Record<string,string>={dashboard:'/',trainer_courses:'/trainer/courses',trainer_exams:'/trainer/exams',trainer_grades:'/trainer/grades',trainer_blackboard:'/trainer/blackboard',trainer_training:'/trainer/training',trainer_advising:'/trainer/advising',trainer_development:'/trainer/development',trainer_assignments:'/trainer/assignments',trainer_exchange:'/trainer/exchange',trainer_portfolio:'/trainer/portfolio',trainer_alerts:'/trainer/alerts',tasks:'/tasks',users:'/users',profile:'/profile',evidence:'/evidence',rayat:'/rayat'};
const titles:Record<string,string>={dashboard:'لوحة المتابعة',trainer_courses:'المقررات',trainer_exams:'الاختبارات',trainer_grades:'تحليل الدرجات',trainer_blackboard:'التدرّب الإلكتروني',trainer_training:'المهام التدريبية',trainer_advising:'الإرشاد الأكاديمي',trainer_development:'التطور المهني',trainer_assignments:'التكليفات',trainer_exchange:'تبادل الخبرات',trainer_portfolio:'ملف الإنجاز',trainer_alerts:'التنبيهات والمهام والمواعيد المهمة',tasks:'المهام والتكليفات',users:'إدارة المستخدمين',profile:'ملفي الشخصي',evidence:'الشواهد',rayat:'تقارير رايات'};
const viewFromPath=()=>Object.keys(paths).find(k=>paths[k]===window.location.pathname)||'unknown';
function WorkspaceNav({nav,view,navigate}:{nav:{key:string;label:string;icon:typeof Users}[];view:string;navigate:(next:string)=>void}){
 const {setOpenMobile}=useSidebar();
 return <SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.key}><SidebarMenuButton asChild isActive={view===n.key}><a href={paths[n.key]} aria-current={view===n.key?'page':undefined} onClick={e=>{if(e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();setOpenMobile(false);navigate(n.key)}}><n.icon/><span>{n.label}</span></a></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>
}
function Vacant({title,description,icon:Icon=Layers}:{title:string;description:string;icon?:typeof Layers}){return <Empty><EmptyHeader><EmptyMedia variant="icon"><Icon/></EmptyMedia><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader></Empty>}
function Login({onLogin}:{onLogin:(user:User,csrf:string)=>void}){
 const[show,setShow]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget);try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:data.get('username'),password:data.get('password')})});const result=await r.json() as {error?:string;user:User;csrf:string};if(!r.ok)throw new Error(result.error);onLogin(result.user,result.csrf)}catch(e){setError(e instanceof Error?e.message:'تعذر الاتصال. حاول مجددًا.')}finally{setBusy(false)}}
 return <main className="login-layout"><div className="login-shell"><section className="login-story"><img className="institution-logo" src="/tvtc-logo-white.svg" alt="المؤسسة العامة للتدريب التقني والمهني" width="297" height="93"/><div className="story-center"><p className="login-description">منصة لمتابعة وتنظيم بيانات القسم ودعم القرار</p><div className="story-line"/><div className="story-tags"><span>رئيس القسم</span><span>مدرب</span><span>وكيل</span><span>عميد</span></div></div><small>قسم التقنية الكهربائية · الكلية التقنية بالدائر</small></section><section className="login-form-area"><div className="login-card"><span className="soft-icon"><ShieldCheck/></span><h2>أهلًا بعودتك</h2><p className="muted">سجّل دخولك إلى مساحة عملك</p><form onSubmit={submit}><label htmlFor="username">اسم المستخدم</label><Input id="username" name="username" autoComplete="username" dir="ltr" required maxLength={40} placeholder="اسم المستخدم"/><label htmlFor="password">كلمة المرور</label><div className="password-field"><Input id="password" name="password" type={show?'text':'password'} autoComplete="current-password" dir="ltr" required maxLength={128}/><button type="button" aria-label={show?'إخفاء كلمة المرور':'إظهار كلمة المرور'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{error&&<div role="alert" className="error">{error}</div>}<Button disabled={busy} className="login-button" type="submit">{busy?'جارٍ تسجيل الدخول…':'تسجيل الدخول'}</Button></form><p className="login-help">للحصول على حساب أو إعادة تعيين كلمة المرور، تواصل مع رئيس القسم.</p></div></section></div></main>
}
function FirstPasswordChange({user,csrf,onChanged,onLogout}:{user:User;csrf:string;onChanged:()=>void;onLogout:()=>void}){
 const[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const data=new FormData(e.currentTarget),password=String(data.get('password')||''),confirmation=String(data.get('confirmation')||'');if(password!==confirmation){setError('كلمتا المرور غير متطابقتين.');return}setBusy(true);try{const r=await fetch('/api/auth/password',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({password})}),d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);onChanged()}catch(e){setError(e instanceof Error?e.message:'تعذر تحديث كلمة المرور.')}finally{setBusy(false)}}
 return <main className="login-layout"><div className="login-shell"><section className="login-story"><img className="institution-logo" src="/tvtc-logo-white.svg" alt="المؤسسة العامة للتدريب التقني والمهني" width="297" height="93"/><div className="story-center"><p className="login-description">أمان حسابك يبدأ بكلمة مرور خاصة بك</p><div className="story-line"/></div><small>قسم التقنية الكهربائية · الكلية التقنية بالدائر</small></section><section className="login-form-area"><div className="login-card"><span className="soft-icon"><ShieldCheck/></span><h2>تغيير كلمة المرور المؤقتة</h2><p className="muted">مرحبًا {user.display_name}، اختر كلمة مرور جديدة قبل متابعة استخدام المنصة.</p><form onSubmit={submit}><label htmlFor="first-password">كلمة المرور الجديدة</label><Input id="first-password" name="password" type="password" autoComplete="new-password" dir="ltr" required minLength={6} maxLength={128}/><small className="muted">٦ أحرف على الأقل.</small><label htmlFor="confirm-password">تأكيد كلمة المرور</label><Input id="confirm-password" name="confirmation" type="password" autoComplete="new-password" dir="ltr" required minLength={6} maxLength={128}/>{error&&<div role="alert" className="error">{error}</div>}<Button disabled={busy} className="login-button" type="submit">{busy?'جارٍ الحفظ…':'حفظ كلمة المرور الجديدة'}</Button></form><Button variant="ghost" disabled={busy} onClick={onLogout}>تسجيل الخروج</Button></div></section></div></main>
}
export default function Platform(){
 const[user,setUser]=useState<User|null>(null),[csrf,setCsrf]=useState(''),[loading,setLoading]=useState(true),[bootError,setBootError]=useState('');
 const[view,setView]=useState('dashboard'),[data,setData]=useState<Dashboard|null>(null),[accounts,setAccounts]=useState<User[]>([]),[profile,setProfile]=useState<Profile|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[viewLoading,setViewLoading]=useState(false);
 const[displayOpen,setDisplayOpen]=useState(false),[layout,setLayout]=useState<Layout>(defaultLayout),[editUser,setEditUser]=useState<User|null>(null),[accountOpen,setAccountOpen]=useState(false),[newRole,setNewRole]=useState<Role>('trainer'),[newActive,setNewActive]=useState(true),[isTest,setIsTest]=useState(false),[newStaffNumber,setNewStaffNumber]=useState(''),[newUsername,setNewUsername]=useState(''),[formError,setFormError]=useState('');
 const currentUserId=useRef('');currentUserId.current=user?.id||'';
 const canEdit=!!user&&['head','trainer'].includes(user.role),isHead=user?.role==='head',isTrainer=user?.role==='trainer';
 const trainerViews=['trainer_courses','trainer_exams','trainer_grades','trainer_blackboard','trainer_training','trainer_advising','trainer_development','trainer_exchange','trainer_assignments','trainer_portfolio','trainer_alerts'];
 const allowed=view==='dashboard'||(isTrainer&&trainerViews.includes(view))||(canEdit&&view==='profile')||(isHead&&['users','rayat','tasks'].includes(view))||(canEdit&&view==='evidence');
 async function api<T=Record<string,unknown>>(path:string,method='GET',body?:unknown){const r=await fetch('/api/'+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},...(body===undefined?{}:{body:JSON.stringify(body)})});const result=await r.json() as {error?:string;user:User;csrf:string};if(r.status===401){setUser(null);setData(null);setAccounts([]);setProfile(null)}if(!r.ok)throw new Error(result.error||'تعذر إتمام الطلب.');return result as T}
 useEffect(()=>{setView(viewFromPath());const pop=()=>setView(viewFromPath());window.addEventListener('popstate',pop);fetch('/api/auth/me').then(async r=>{if(r.status===401)return;const d=await r.json() as {error?:string;user:User;csrf:string};if(!r.ok)throw new Error(d.error);setUser(d.user);setCsrf(d.csrf)}).catch(()=>setBootError('تعذر الاتصال بالمنصة. أعد تحميل الصفحة.')).finally(()=>setLoading(false));return()=>window.removeEventListener('popstate',pop)},[]);
 function navigate(next:string){if(window.location.pathname!==paths[next])window.history.pushState({},'',paths[next]);setView(next);setError('');setNotice('');requestAnimationFrame(()=>{window.scrollTo({top:0,behavior:'instant'});document.getElementById('page-title')?.focus({preventScroll:true})})}
 async function refresh(){if(!user||!allowed)return;setError('');setViewLoading(true);try{if(view==='dashboard'&&!isTrainer){const d=await api<Dashboard>('dashboard');if(currentUserId.current===user.id){setData(d);setLayout(d.layout)}}if(view==='users'){const d=await api<{users:User[]}>('users');if(currentUserId.current===user.id)setAccounts(d.users);}if(view==='profile'){const d=await api<{profile:Profile}>('profiles/'+user.id);if(currentUserId.current===user.id)setProfile(d.profile);}}catch(e){setError((e as Error).message)}finally{setViewLoading(false)}}
 useEffect(()=>{setData(null);setAccounts([]);setProfile(null);void refresh()},[user?.id,view]);
 useEffect(()=>{
  if(!user||view!=='dashboard')return;
  const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context)return;
  const controller=new AbortController();
  try{context.registerTool({name:'read_department_dashboard',description:'Read the signed-in user’s authorized dashboard indicators.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('No input fields allowed');return api('dashboard')}},{signal:controller.signal})}catch{/* Optional browser capability. */}
  return()=>controller.abort();
 },[user?.id,view,csrf]);
 async function logout(){setBusy(true);try{await api('auth/logout','POST',{});setUser(null);setCsrf('');setData(null);setAccounts([]);setProfile(null);navigate('dashboard')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function saveLayout(next:Layout){setBusy(true);try{await api('dashboard/preferences','PUT',next);setLayout(next);setData(d=>d?{...d,layout:next}:d);setDisplayOpen(false);setNotice('تم حفظ طريقة عرضك. قيم المؤشرات لم تتغير.')}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
 async function saveAvatar(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const r=await fetch('/api/profile/avatar',{method:'POST',headers:{'X-CSRF-Token':csrf},body:f});const d=await r.json() as {error?:string;avatarUpdatedAt:number};if(!r.ok)throw new Error(d.error);setUser(u=>u?{...u,avatar_updated_at:d.avatarUpdatedAt}:u);setNotice('تم حفظ الصورة الشخصية.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function saveProfile(value:{specialty:string;office_hours:OfficeHour[]}){setBusy(true);try{await api('profiles/'+user!.id,'PATCH',value);setProfile(p=>p?{...p,...value}:p);setNotice('حُفظت بيانات الملف والساعات المكتبية.')}finally{setBusy(false)}}
 function openAccount(target:User|null){setEditUser(target);setNewRole(target?.role||'trainer');setNewActive(target?.active===0?false:true);setIsTest(!!target?.is_test);setNewStaffNumber(target?.staff_number||'');setNewUsername(target?.username||'');setFormError('');setAccountOpen(true)}
 async function saveAccount(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setFormError('');const f=new FormData(e.currentTarget);const password=String(f.get('password')||'');const staffNumber=newStaffNumber.trim()||null;try{if(editUser){await api('users/'+editUser.id,'PATCH',{display_name:f.get('display_name'),...(newRole!==editUser.role?{role:newRole}:{}),...(newActive!==!!editUser.active?{active:newActive}:{}),...(staffNumber!== (editUser.staff_number||null)?{staff_number:staffNumber}:{}),...(password?{password}:{})})}else{const username=newRole==='trainer'&&staffNumber?'00'+staffNumber.replace(/^0+/,''):String(f.get('username')||'');await api('users','POST',{username,display_name:f.get('display_name'),password,role:newRole,is_test:isTest,staff_number:staffNumber})}setAccountOpen(false);setNotice(editUser?'تم تحديث الحساب وربطه ببيانات التدريب.':'تم إنشاء الحساب.');if(editUser?.id===user?.id&&password){setUser(null);return}if(editUser?.id===user?.id)setUser(u=>u?{...u,display_name:String(f.get('display_name')),staff_number:staffNumber}:u);await refresh()}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
 if(loading)return <main className="boot"><Skeleton className="h-12 w-64"/><p>جارٍ فتح مساحة العمل…</p></main>;
 if(bootError)return <main className="boot"><p role="alert">{bootError}</p><Button onClick={()=>window.location.reload()}>إعادة المحاولة</Button></main>;
 if(!user)return <Login onLogin={(u,c)=>{setUser(u);setCsrf(c);setError('');setNotice('');navigate('dashboard')}}/>;
  if(user.must_change_password)return <FirstPasswordChange user={user} csrf={csrf} onChanged={()=>{setUser(u=>u?{...u,must_change_password:0}:u);setNotice('تم تغيير كلمة المرور. يمكنك الآن استخدام حسابك.')}} onLogout={()=>void logout()}/>;
 const nav=isTrainer?[{key:'dashboard',label:'لوحة المدرب',icon:LayoutDashboard},{key:'trainer_courses',label:'المقررات',icon:BookOpen},{key:'trainer_exams',label:'الاختبارات',icon:FileCheck2},{key:'trainer_grades',label:'تحليل الدرجات',icon:FileSpreadsheet},{key:'trainer_blackboard',label:'التدرّب الإلكتروني',icon:Layers},{key:'trainer_training',label:'المهام التدريبية',icon:ClipboardList},{key:'trainer_advising',label:'الإرشاد الأكاديمي',icon:GraduationCap},{key:'trainer_development',label:'التطور المهني',icon:Activity},{key:'trainer_assignments',label:'التكليفات',icon:ClipboardList},{key:'trainer_exchange',label:'تبادل الخبرات',icon:Users},{key:'trainer_portfolio',label:'ملف الإنجاز',icon:FileSpreadsheet},{key:'evidence',label:'الشواهد والمراجعات',icon:FileCheck2},{key:'trainer_alerts',label:'التنبيهات والمواعيد',icon:Lightbulb},{key:'profile',label:'ملفي الشخصي',icon:UserRound}]:[{key:'dashboard',label:'لوحة المتابعة',icon:LayoutDashboard},...(canEdit?[{key:'evidence',label:'الشواهد',icon:FileSpreadsheet}]:[]),...(isHead?[{key:'tasks',label:'المهام والتكليفات',icon:ClipboardList},{key:'users',label:'إدارة المستخدمين',icon:Users},{key:'rayat',label:'تقارير رايات',icon:FileSpreadsheet}]:[]),...(canEdit?[{key:'profile',label:'ملفي الشخصي',icon:UserRound}]:[])];
 return <SidebarProvider><a className="skip-link" href="#main-content">انتقل إلى المحتوى</a><Sidebar side="right"><SidebarHeader className="side-brand"><img src="/tvtc-logo-white.svg" alt="المؤسسة العامة للتدريب التقني والمهني" width="220" height="69"/><div className="department-label">قسم التقنية الكهربائية<small>الكلية التقنية بالدائر</small></div></SidebarHeader><SidebarContent className="side-content"><span className="nav-caption">مساحة العمل</span><WorkspaceNav nav={nav} view={view} navigate={navigate}/><div className="access-note"><ShieldCheck size={19}/><div>{canEdit?'مساحة مخصصة لدورك':'الاطلاع على مؤشرات القسم'}<small>{canEdit?'تظهر لك البيانات وفق صلاحيات حسابك.':'صلاحية قراءة فقط'}</small></div></div></SidebarContent><SidebarFooter className="side-footer"><AccountAvatar user={user}/><div><b>{user.display_name}</b><small>{roleLabels[user.role]}</small></div></SidebarFooter></Sidebar><SidebarInset className="main-inset"><header className="topbar"><div><SidebarTrigger aria-label="فتح القائمة الجانبية"/><span>قسم التقنية الكهربائية</span><span className="divider">/</span><b>{view==='dashboard'&&isTrainer?'لوحة المدرب':titles[view]||'صفحة غير متاحة'}</b></div><div><div className="header-account"><AccountAvatar user={user}/><div><strong>{user.display_name}</strong><small>{roleLabels[user.role]}</small></div></div>{!!user.is_test&&<span className="test-badge">حساب تجريبي</span>}<Button variant="ghost" aria-label="تسجيل الخروج" disabled={busy} onClick={logout}><LogOut size={17}/><span>تسجيل الخروج</span></Button></div></header><main className="workspace" id="main-content" tabIndex={-1}><div className="page-heading"><div><h1 id="page-title" tabIndex={-1}>{view==='dashboard'?(isTrainer?'لوحة المدرب':'لوحة متابعة القسم'):titles[view]||'صفحة غير متاحة'}</h1><p className="muted">{view==='dashboard'?(isTrainer?'مؤشرات إنجازك التدريبي والمهني، ومتابعة التكليفات والمواعيد.':'مؤشرات القسم الأساسية وفق البيانات المسجلة.'):(view==='users'?'الحسابات والأدوار وصلاحيات الوصول.':view==='profile'?'بياناتك الأساسية وصورتك الشخصية.':view==='evidence'?'رفع الشواهد ومتابعة مراجعاتها.':view==='rayat'?'رفع تقارير رايات والتحقق من بيانات القسم.':'')}</p></div>{view==='dashboard'&&isHead&&<Button variant="outline" onClick={()=>{setLayout(data?.layout||defaultLayout);setFormError('');setDisplayOpen(true)}} disabled={!data}><SlidersHorizontal size={17}/>طريقة العرض</Button>}{view==='users'&&isHead&&<Button onClick={()=>openAccount(null)}><Plus size={18}/>إضافة مستخدم</Button>}</div>{error&&<div role="alert" className="error">{error}<Button variant="ghost" onClick={refresh}>إعادة المحاولة</Button></div>}{notice&&<div role="status" className="success">{notice}</div>}
 {!allowed?<section className="panel"><Vacant icon={LockKeyhole} title="هذه الصفحة غير متاحة لحسابك" description="يمكنك متابعة المؤشرات والبيانات المسموح بها من القائمة الجانبية."/></section>:viewLoading?<div className="metric-grid">{[1,2,3,4].map(i=><Skeleton key={i} className="h-40 rounded-xl"/>)}</div>:<Suspense fallback={<div role="status" className="route-loading">جارٍ تحميل الصفحة…</div>}>
 {isTrainer&&(view==='dashboard'||trainerViews.includes(view))?<TrainerWorkspace user={user} csrf={csrf} section={view==='dashboard'?'overview':view==='trainer_courses'?'courses':view==='trainer_exams'?'exams':view==='trainer_grades'?'grades':view==='trainer_blackboard'?'blackboard':view==='trainer_training'?'training':view==='trainer_advising'?'advising':view==='trainer_development'?'development':view==='trainer_assignments'?'assignments':view==='trainer_exchange'?'exchange':view==='trainer_alerts'?'alerts':'portfolio'}/>:view==='dashboard'&&data&&<><div className="scope-strip"><span><ShieldCheck size={17}/>{canEdit?'نطاق العرض: جميع بيانات القسم':'نطاق العرض: مؤشرات القسم · قراءة فقط'}</span><small>آخر قراءة: {new Date(data.asOf).toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'})}</small></div><section className={'metric-grid '+data.layout.density}>{metrics.filter(m=>data.metrics[m.id]!==null&&!data.layout.hidden.includes(m.id)).map(m=><article className="metric-card" key={m.id}><div><span className={'metric-icon '+m.color}><m.icon size={23}/></span><span className="metric-label">{m.title}</span></div><strong>{(data.metrics[m.id]??0).toLocaleString('ar-SA-u-nu-latn')}</strong><p>{m.id==='trainers'?'الحسابات النشطة · دون التجريبية':'وفق البيانات المسجلة'}</p></article>)}</section><RayatIndicators data={data.rayat} isHead={isHead}/>{data.layout.hidden.length>=4&&<section className="panel"><Vacant title="المؤشرات مخفية في طريقة عرضك" description="يمكنك إظهارها من إعدادات طريقة العرض."/></section>}{isHead&&<DepartmentActions csrf={csrf}/>}<div className="dashboard-grid"><section className="panel"><div className="panel-title"><div><h3>المؤشرات التدريبية</h3><p>تعتمد هذه المساحة على بيانات القسم المعتمدة.</p></div><BookOpen size={22}/></div><Vacant title="لا تتوفر تفاصيل المؤشرات التدريبية حاليًا" description="سيظهر هنا تفصيل المؤشرات عند توفره." icon={GraduationCap}/></section><section className="panel"><div className="panel-title"><div><h3>نطاق الوصول</h3><p>{roleLabels[user.role]}</p></div><ShieldCheck size={22}/></div><div className="permission-list">{(isHead?['إدارة حسابات القسم وصلاحياتها','الاطلاع على جميع مؤشرات القسم','تخصيص العرض دون تغيير المؤشرات']:['الاطلاع على مؤشرات القسم المجمعة','قراءة فقط دون تعديل البيانات','لا تشمل الصلاحية إدارة الحسابات أو بيانات الأشخاص']).map(permission=><div key={permission}><Check/><span>{permission}</span></div>)}</div><div className="panel-note">المؤشرات تُحسب من البيانات المحفوظة، ولا تُدخل يدويًا.</div></section></div></>}
  {view==='users'&&<section className="panel"><div className="panel-title"><div><h3>حسابات المستخدمين <span className="count">{accounts.length.toLocaleString('ar-SA')}</span></h3><p>اربط حساب كل مدرب برقمه الوظيفي كما يظهر في تقرير رايات (SL03).</p></div></div><Table><TableHeader><TableRow><TableHead>المستخدم</TableHead><TableHead>اسم المستخدم</TableHead><TableHead>الرقم الوظيفي</TableHead><TableHead>الدور</TableHead><TableHead>الحالة</TableHead><TableHead>الإجراء</TableHead></TableRow></TableHeader><TableBody>{accounts.map(a=><TableRow key={a.id}><TableCell><b>{a.display_name}</b>{!!a.is_test&&<small className="table-sub">حساب تجريبي</small>}</TableCell><TableCell><span dir="ltr">{a.username}</span></TableCell><TableCell><span dir="ltr">{a.role==='trainer'?a.staff_number||'غير مرتبط':'—'}</span></TableCell><TableCell>{roleLabels[a.role]}</TableCell><TableCell><span className={a.active?'status-active':'status-inactive'}>{a.active?'نشط':'موقوف'}</span>{!!a.must_change_password&&<small className="table-sub">تغيير كلمة المرور مطلوب عند أول دخول</small>}</TableCell><TableCell><Button variant="outline" size="sm" onClick={()=>openAccount(a)} aria-label={'إدارة حساب '+a.username}><Settings2 size={15}/>إدارة</Button></TableCell></TableRow>)}</TableBody></Table></section>}
 {view==='profile'&&profile&&<section className="panel profile-panel"><div className="panel-title"><div><h3>{profile.display_name}</h3><p dir="ltr">{profile.username}</p></div><UserRound/></div><div className="profile-avatar"><AccountAvatar user={user}/><form onSubmit={saveAvatar}><label htmlFor="avatar-file">الصورة الشخصية</label><Input id="avatar-file" name="file" type="file" required accept=".png,.jpg,.jpeg,.webp,image/png,image/jpeg,image/webp"/><small className="muted">PNG أو JPG أو WebP، حتى ٢ ميغابايت.</small><Button type="submit" disabled={busy}>رفع الصورة</Button></form></div><ProfileEditor key={profile.id} profile={profile} onSave={saveProfile} busy={busy}/></section>}
 {view==='evidence'&&<EvidencePage user={user} csrf={csrf}/>}
  {view==='rayat'&&<RayatPage csrf={csrf}/>}
 {view==='tasks'&&isHead&&<HeadTasks csrf={csrf}/>}
  </Suspense>}<footer className="workspace-footer"><span>قسم التقنية الكهربائية</span><span>منصة متابعة أعمال القسم</span></footer></main></SidebarInset>
 <Dialog open={displayOpen} onOpenChange={setDisplayOpen}><DialogContent dir="rtl" className="app-dialog"><DialogHeader><DialogTitle>طريقة عرض لوحتك</DialogTitle><DialogDescription>تُحفظ لحسابك فقط. لا تغيّر قيم البيانات.</DialogDescription></DialogHeader><label>تنسيق البطاقات</label><Select dir="rtl" value={layout.density} onValueChange={v=>setLayout({...layout,density:v as Layout['density']})}><SelectTrigger aria-label="تنسيق البطاقات"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="comfortable">قياسي</SelectItem><SelectItem value="compact">مضغوط</SelectItem></SelectContent></Select>{metrics.filter(m=>!isTrainer||m.id!=='trainers').map(m=><div className="switch-row" key={m.id}><label htmlFor={'show-'+m.id}>{isTrainer?m.personal:m.title}</label><Switch id={'show-'+m.id} checked={!layout.hidden.includes(m.id)} onCheckedChange={checked=>setLayout({...layout,hidden:checked?layout.hidden.filter(k=>k!==m.id):[...layout.hidden,m.id]})}/></div>)}{formError&&<div role="alert" className="error">{formError}</div>}<div className="dialog-actions"><Button disabled={busy} onClick={()=>saveLayout(layout)}>حفظ العرض</Button><Button disabled={busy} variant="outline" onClick={()=>saveLayout(defaultLayout)}><RotateCcw size={16}/>استعادة الافتراضي</Button></div></DialogContent></Dialog>
 <Dialog open={accountOpen} onOpenChange={setAccountOpen}><DialogContent dir="rtl" className="app-dialog"><DialogHeader><DialogTitle>{editUser?'إدارة الحساب':'إضافة مستخدم'}</DialogTitle><DialogDescription>{editUser?'حدّث البيانات أو الدور أو أعد تعيين كلمة المرور.':'أنشئ حسابًا وحدد دوره في القسم.'}</DialogDescription></DialogHeader><form onSubmit={saveAccount}><label htmlFor="display_name">الاسم الظاهر</label><Input id="display_name" name="display_name" required minLength={2} maxLength={80} defaultValue={editUser?.display_name||''}/>{!editUser&&<><label htmlFor="new_username">اسم المستخدم</label><Input id="new_username" name="username" required minLength={3} maxLength={40} pattern="[A-Za-z0-9._\-]+" dir="ltr" autoComplete="off" value={newRole==='trainer'&&newStaffNumber?'00'+newStaffNumber.replace(/^0+/,''):newUsername} onChange={e=>setNewUsername(e.target.value)} readOnly={newRole==='trainer'&&!!newStaffNumber}/>{newRole==='trainer'&&newStaffNumber&&<small className="muted">سيكون اسم المستخدم 00 متبوعًا برقمك الوظيفي بعد حذف الأصفار البادئة.</small>}</>}<label>الدور</label><Select dir="rtl" value={newRole} disabled={editUser?.id===user.id} onValueChange={v=>setNewRole(v as Role)}><SelectTrigger aria-label="الدور"><SelectValue/></SelectTrigger><SelectContent>{roles.map(r=><SelectItem value={r} key={r}>{roleLabels[r]}</SelectItem>)}</SelectContent></Select>{newRole==='trainer'&&<><label htmlFor="staff_number">الرقم الوظيفي في رايات</label><Input id="staff_number" inputMode="numeric" maxLength={12} dir="ltr" value={newStaffNumber} onChange={e=>setNewStaffNumber(e.target.value.replace(/\D/g,''))} placeholder="مثال: 31464"/><small className="muted">يُستخدم لربط حساب المدرب بالشعب المسندة إليه في تقرير SS01.</small></>}<label htmlFor="new_password">{editUser?'كلمة مرور جديدة (اختياري)':'كلمة المرور'}</label><Input id="new_password" name="password" type="password" autoComplete="new-password" dir="ltr" required={!editUser} minLength={6} maxLength={128}/><small className="muted">٦ أحرف على الأقل. {editUser?'اتركها فارغة للإبقاء على كلمة المرور الحالية.':''}</small>{editUser?<div className="switch-row"><label htmlFor="account_active">الحساب نشط</label><Switch id="account_active" disabled={editUser.id===user.id} checked={newActive} onCheckedChange={setNewActive}/></div>:<div className="switch-row"><label htmlFor="is_test">حساب تجريبي (يُستبعد من الإحصائيات)</label><Switch id="is_test" checked={isTest} onCheckedChange={setIsTest}/></div>}{formError&&<div className="error" role="alert">{formError}</div>}<div className="dialog-actions"><Button disabled={busy} type="submit">{busy?'جارٍ الحفظ…':'حفظ الحساب'}</Button><Button type="button" variant="outline" onClick={()=>setAccountOpen(false)}>إلغاء</Button></div></form></DialogContent></Dialog>
 </SidebarProvider>
}











