'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
export type OfficeHour={day:number;start:string;end:string};
export default function ProfileEditor({profile,onSave,busy}:{profile:{specialty:string;office_hours?:OfficeHour[]};onSave:(value:{specialty:string;office_hours:OfficeHour[]})=>Promise<void>;busy:boolean}){
 const[specialty,setSpecialty]=useState(profile.specialty),[hours,setHours]=useState<OfficeHour[]>(profile.office_hours||[]),[error,setError]=useState('');
 const days=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
 return <form className="profile-form professional-form" onSubmit={async e=>{e.preventDefault();setError('');if(hours.some(h=>h.start>=h.end)){setError('يجب أن يكون وقت نهاية الفترة بعد بدايتها.');return}try{await onSave({specialty,office_hours:hours})}catch(e){setError((e as Error).message)}}}><label>التخصص<input value={specialty} maxLength={120} onChange={e=>setSpecialty(e.target.value)}/></label><div className="section-heading"><div><h3>الساعات المكتبية</h3><p>حدد أيام استقبال المتدربين والفترات المتاحة بتوقيت المملكة.</p></div><Button type="button" variant="outline" disabled={hours.length>=21} onClick={()=>setHours([...hours,{day:0,start:'09:00',end:'10:00'}])}>إضافة فترة</Button></div>{hours.map((h,i)=><div className="office-row" key={i}><label>اليوم<select value={h.day} onChange={e=>setHours(hours.map((v,j)=>i===j?{...v,day:+e.target.value}:v))}>{days.map((d,n)=><option key={n} value={n}>{d}</option>)}</select></label><label>من<input aria-label={'بداية الفترة '+(i+1)} type="time" required value={h.start} onChange={e=>setHours(hours.map((v,j)=>i===j?{...v,start:e.target.value}:v))}/></label><label>إلى<input aria-label={'نهاية الفترة '+(i+1)} type="time" required value={h.end} onChange={e=>setHours(hours.map((v,j)=>i===j?{...v,end:e.target.value}:v))}/></label><Button type="button" variant="ghost" onClick={()=>setHours(hours.filter((_,j)=>j!==i))}>حذف الفترة</Button></div>)}{!hours.length&&<p className="help">لم تُحدد ساعات مكتبية بعد.</p>}{error&&<p role="alert" className="error">{error}</p>}<Button disabled={busy} type="submit">{busy?'جارٍ الحفظ…':'حفظ بيانات الملف والساعات المكتبية'}</Button></form>;
}
