'use client';
import {useEffect,useState,FormEvent} from 'react';
import {FileSpreadsheet,UploadCloud,ShieldCheck,AlertCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {reportKinds,ReportKind} from '@/lib/rayat';

type Summary={rows:number;departmentRows:number;trainees?:number;sections?:number;courses?:number;withdrawn?:number;dismissed?:number;deprived?:number;trainers?:number;capacity?:number;enrolled?:number;remaining?:number;overCapacity?:number;staff?:number;continuingRegistrations?:number;deprivedRegistrations?:number;dismissedRegistrations?:number;withdrawnRegistrations?:number;withUnexcusedAbsence?:number;deletedCourseRows?:number;remoteSections?:number;remoteRegistrations?:number;confirmedRemoteSections?:number};
type Report={id:string;kind:ReportKind;term:string|null;normalized_term:string|null;original_filename:string;byte_size:number;summary:Summary;created_at:number;active:number};
const kinds=Object.keys(reportKinds) as ReportKind[];
const names:Record<string,string>={rows:'إجمالي سجلات التقرير',departmentRows:'سجلات القسم',trainees:'المتدربون',sections:'الشعب التدريبية',courses:'المقررات',withdrawn:'المنسحبون',dismissed:'المطوي قيدهم',deprived:'المحرومون',trainers:'المدربون في الجدول',capacity:'السعة',enrolled:'تسجيلات المقررات',remaining:'صافي المقاعد المتبقية',overCapacity:'شعب تجاوزت سعتها',staff:'أعضاء هيئة التدريب',continuingRegistrations:'تسجيلات المستمرين',deprivedRegistrations:'تسجيلات المحرومين',dismissedRegistrations:'تسجيلات المطوي قيدهم',withdrawnRegistrations:'تسجيلات المنسحبين',withUnexcusedAbsence:'متدربون لديهم غياب دون عذر',deletedCourseRows:'سجلات مقررات محذوفة',remoteSections:'شعب التدريب عن بُعد',remoteRegistrations:'تسجيلات شعب التدريب عن بُعد',confirmedRemoteSections:'شعب صُحح تصنيفها بتأكيد القسم'};
const primary:Record<ReportKind,(keyof Summary)[]>={SF01:['trainees','sections','courses','withdrawn','dismissed','deprived'],SS01:['sections','enrolled','capacity','remaining','overCapacity','trainers','remoteSections','remoteRegistrations','confirmedRemoteSections'],SL03:['staff'],SO08:['courses','enrolled','continuingRegistrations','deprivedRegistrations','dismissedRegistrations','withdrawnRegistrations'],SO01:['trainees','courses','withUnexcusedAbsence','deprived','deletedCourseRows'],SF06:['trainees']};
export default function RayatPage({csrf}:{csrf:string}){
 const[reports,setReports]=useState<Report[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<ReportKind|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function refresh(){const r=await fetch('/api/rayat');const data=await r.json() as {error?:string;reports?:Report[]};if(!r.ok)throw new Error(data.error||'تعذر قراءة التقارير.');setReports(data.reports||[])}
 useEffect(()=>{let live=true;fetch('/api/rayat').then(async r=>{const data=await r.json() as {error?:string;reports?:Report[]};if(!r.ok)throw new Error(data.error||'تعذر قراءة التقارير.');if(live)setReports(data.reports||[])}).catch(e=>{if(live)setError((e as Error).message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[]);
 async function upload(event:FormEvent<HTMLFormElement>,kind:ReportKind){event.preventDefault();setError('');setNotice('');setBusy(kind);const form=event.currentTarget;const data=new FormData(form);data.set('kind',kind);
  try{const r=await fetch('/api/rayat',{method:'POST',headers:{'X-CSRF-Token':csrf},body:data});const result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'تعذر رفع التقرير.');await refresh();form.reset();setNotice('تم فحص التقرير وحفظه. تظهر أرقام القسم أدناه.')}
  catch(e){setError((e as Error).message)}finally{setBusy(null)}
 }
 return <div className="rayat-page"><div className="rayat-intro"><ShieldCheck size={19}/><p>تُفحص ملفات CSV قبل حفظها. يمكن لرئيس القسم رفع التقارير فقط؛ ولا تُعرض بيانات الأشخاص في الملخص. رُبط الرمز ١٤٤٧١٠ باسم «الفصل التدريبي الأول ١٤٤٨» بناءً على تأكيد القسم.</p></div>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="success" role="status">{notice}</p>}
 <div className="rayat-grid">{kinds.map(kind=>{const latest=reports.find(r=>r.kind===kind&&r.active===1);return <section className="panel rayat-card" key={kind}><div className="panel-title"><div><span className="rayat-code">{kind}</span><h3>{reportKinds[kind].label}</h3></div><FileSpreadsheet size={22}/></div><div className="rayat-card-body"><p className="muted">{kind==='SF06'?'يقبل التقرير الخالي من السجلات. لا يتضمن الملف فصلًا تدريبيًا؛ أكد القسم أن العينة الحالية للفصل التدريبي الأول ١٤٤٨.':kind==='SO01'?'يغطي غياب متدربي القسم في جميع مقرراتهم، بما فيها مقررات خارج شعب القسم؛ لذلك قد يختلف عدد المحرومين عن SF01.':kind==='SO08'?'الأعداد حسب المقرر وتمثل تسجيلات؛ قد يتكرر المتدرب بين المقررات.':kind==='SS01'?'تُحتسب المقاعد مرة واحدة لكل شعبة. صُحح تصنيف شعبتين إلى التدريب عن بُعد بتأكيد القسم، مع بقاء الملف الأصلي كما صدر من رايات.':kind==='SL03'?'كشف أعضاء القسم المعتمد؛ قد يختلف عن قائمة المدربين المجدولين بسبب التكليف أو الابتعاث.':'ملف تسجيل المتدربين الذي يتضمن رقم المتدرب وحالة التسجيل؛ ملف السعة والمقاعد يتبع SS01.'}</p><form onSubmit={e=>upload(e,kind)}><label htmlFor={'rayat-'+kind}>اختر ملف CSV</label><input id={'rayat-'+kind} name="file" type="file" accept=".csv,text/csv" required disabled={busy!==null}/><Button type="submit" disabled={busy!==null}><UploadCloud size={17}/>{busy===kind?'جارٍ الفحص والحفظ…':'رفع التقرير'}</Button></form>{latest?<div className="rayat-summary"><b>آخر نسخة محفوظة</b><small>{latest.original_filename}</small><small>{latest.term||'لم يرد فصل تدريبي في الملف'} · {new Date(latest.created_at).toLocaleString('ar-SA')}</small><div className="rayat-values">{primary[kind].map(key=><div key={key}><strong>{Number(latest.summary[key]||0).toLocaleString('ar-SA-u-nu-latn')}</strong><span>{names[key]}</span></div>)}</div><small>سجلات القسم: {latest.summary.departmentRows.toLocaleString('ar-SA-u-nu-latn')} من {latest.summary.rows.toLocaleString('ar-SA-u-nu-latn')}</small></div>:<p className="rayat-empty"><AlertCircle size={16}/>{loading?'جارٍ تحميل التقارير…':'لم يُرفع هذا التقرير بعد.'}</p>}{reports.some(r=>r.kind===kind&&r.id!==latest?.id)&&<details className='rayat-history'><summary>النسخ والفصول الأخرى</summary>{reports.filter(r=>r.kind===kind&&r.id!==latest?.id).map(r=><div key={r.id}><span>{r.original_filename}</span><small>{r.term||'فصل غير محدد'} · {new Date(r.created_at).toLocaleString('ar-SA')}</small></div>)}</details>}</div></section>})}</div><p className="rayat-footnote">تعتمد أعداد المتدربين وحالاتهم على SF01 فقط، دون طلب تقرير مستقل للأعداد حسب المستوى. لا يُستنتج المستوى التدريبي من المرحلة أو رمز المقرر عند غياب حقل المستوى.</p></div>
}


