'use client';
import {useState,useRef} from 'react';
import {Award,Users,Plus,Paperclip,CalendarDays,CheckCircle2,FolderOpen} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {recordLabel,type WorkRecord} from '@/lib/trainer-domain';
import {EvidenceFiles,EvidenceQueue,EvidenceUploader,useEvidenceQueue,uploadWorkFile} from './trainer-evidence';
export default function TrainerDocumentation({category,records,csrf,onSaved}:{category:'development'|'exchange';records:WorkRecord[];csrf:string;onSaved:()=>Promise<void>}){
 const list=records.filter(r=>r.category===category),development=category==='development',Icon=development?Award:Users;
 const[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[showForm,setShowForm]=useState(()=>!list.length),draft=useRef<string|null>(null),queue=useEvidenceQueue();
 async function save(itemKey:string,status:string,payload:Record<string,unknown>){const response=await fetch('/api/trainer/workspace/records',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({courseKey:'general',category,itemKey,status,payload})}),result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error)}
 return <div className="documentation-workspace"><section className="module-banner"><span className="module-icon"><Icon size={28}/></span><div><span className="eyebrow">ملفك المهني</span><h2>{development?'تعلّم مستمر وأثر مهني':'خبرات تُشارك وممارسات تتطور'}</h2><p>{development?'وثّق الدورات والبرامج وورش العمل في سجلات مستقلة.':'وثّق كل برنامج أو لقاء لتبادل الخبرات في سجل مستقل.'} أرفق شاهدًا واحدًا على الأقل لكل نشاط.</p></div><Button disabled={busy} aria-expanded={showForm} aria-controls="activity-form" onClick={()=>setShowForm(v=>!v)}><Plus size={17}/>{showForm?'طي النموذج وحفظ المسودة':'إضافة نشاط أو متابعة المسودة'}</Button></section>
 <div className="documentation-stats"><span><FolderOpen/>{list.length} نشاطًا معروضًا</span><span><CheckCircle2/>{list.filter(r=>r.status==='done'&&r.files.length).length} موثقًا</span><span><Paperclip/>{list.reduce((n,r)=>n+r.files.length,0)} شاهدًا</span></div>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="success" role="status">{notice}</p>}
 <section hidden={!showForm} id="activity-form" className="panel documentation-form"><div className="section-heading"><div><h3>{development?'إضافة دورة أو برنامج أو ورشة عمل':'إضافة برنامج لتبادل الخبرات'}</h3><p>تبقى المسودة عند طي النموذج في هذه الصفحة. النشاط لا يدخل ضمن نسبة الإنجاز العامة.</p></div><span className="reference-badge">شاهد مطلوب للتوثيق</span></div><form className="professional-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);setBusy(true);setError('');setNotice('');try{if(!queue.entries.length)throw new Error('اختر شاهدًا واحدًا على الأقل.');const payload={title:String(f.get('title')),kind:String(f.get('kind')),date:String(f.get('date')),provider:String(f.get('provider')),notes:String(f.get('notes'))};draft.current||=crypto.randomUUID();await save(draft.current,'not_done',payload);const success=await queue.upload((file,id)=>uploadWorkFile(csrf,category,draft.current!,'general',file,id));if(!success)throw new Error('حُفظت بيانات النشاط. أعد محاولة المرفقات المتعثرة لإكمال توثيقه.');await save(draft.current,'done',payload);draft.current=null;queue.clear();form.reset();setShowForm(false);setNotice('حُفظ النشاط مع شواهده في ملف الإنجاز.')}catch(e){setError((e as Error).message)}finally{try{await onSaved()}catch(e){setError((e as Error).message)}setBusy(false)}}}>
 <div className="form-grid"><label>نوع النشاط<select name="kind"><option>دورة تدريبية</option><option>برنامج تدريبي</option><option>ورشة عمل</option><option>لقاء مهني</option>{!development&&<option>زيارة تبادل خبرات</option>}</select></label><label>اسم النشاط<input name="title" required minLength={3} maxLength={140} placeholder={development?'مثال: السلامة في المنشآت الكهربائية':'مثال: أساليب التدريب العملي بالمحاكاة'}/></label><label>تاريخ التنفيذ<input type="date" name="date" required/></label><label>الجهة المنظمة أو المشاركون<input name="provider" maxLength={180}/></label></div><label>وصف النشاط وأثره المهني<textarea name="notes" required maxLength={2500} rows={3}/></label>
 <div className="attachment-composer"><h4><Paperclip size={18}/>شواهد النشاط</h4><EvidenceQueue queue={queue} disabled={busy}/></div><Button type="submit" disabled={busy||!queue.entries.length}>{busy?'جارٍ حفظ النشاط وشواهده…':queue.entries.some(e=>e.state==='failed')?'استكمال رفع المتعثر وتوثيق النشاط':'حفظ النشاط والشواهد'}</Button></form></section>
 <div className="documentation-records">{list.map(r=><article className="documentation-record panel" key={r.id}><header><span className="module-icon"><Icon size={22}/></span><div><small>{String(r.payload.kind||'نشاط مهني')}</small><h3>{recordLabel(r)}</h3></div><span className={'tw-status '+(r.status==='done'&&r.files.length?'done':'not_done')}>{r.status==='done'&&r.files.length?'موثّق':'بانتظار الشاهد'}</span></header><div className="record-meta"><span><CalendarDays size={15}/>{String(r.payload.date||'تاريخ غير مسجل')}</span>{!!r.payload.provider&&<span>{String(r.payload.provider)}</span>}</div><p>{String(r.payload.notes||'')}</p><EvidenceFiles key={r.id} files={r.files} recordId={r.id} nextCursor={r.filesNextCursor}/><EvidenceUploader csrf={csrf} category={category} itemKey={r.item_key} courseKey="general" onSaved={async complete=>{if(complete)await save(r.item_key,'done',r.payload);await onSaved()}} disabled={busy}/></article>)}</div>{!list.length&&!showForm&&<p className="empty-state">لم تسجل نشاطًا بعد. افتح النموذج لبدء التوثيق.</p>}
 </div>;
}
