'use client';
import {useState,useRef} from 'react';
import {Award,Users,Plus,Paperclip,CalendarDays,CheckCircle2,FolderOpen} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {recordLabel,type WorkRecord} from '@/lib/trainer-domain';
import {EvidenceFiles,EvidencePicker,uploadEvidence,validateEvidenceFiles} from './trainer-evidence';
export default function TrainerDocumentation({category,records,csrf,onSaved}:{category:'development'|'exchange';records:WorkRecord[];csrf:string;onSaved:()=>Promise<void>}){
 const[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[chosen,setChosen]=useState<File[]>([]),[showForm,setShowForm]=useState(false),draft=useRef<string|null>(null);
 const list=records.filter(r=>r.category===category),development=category==='development',Icon=development?Award:Users;
 async function save(itemKey:string,status:string,payload:Record<string,unknown>){const response=await fetch('/api/trainer/workspace/records',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({courseKey:'general',category,itemKey,status,payload})}),result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error)}
 async function append(record:WorkRecord,files:File[]){setBusy(true);setError('');try{await uploadEvidence(csrf,category,record.item_key,'general',files);await save(record.item_key,'done',record.payload);setNotice('أُضيفت الشواهد إلى النشاط، وأصبح موثقًا في ملف الإنجاز.')}catch(e){setError((e as Error).message)}finally{try{await onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}
 return <div className="documentation-workspace"><section className="module-banner"><span className="module-icon"><Icon size={28}/></span><div><span className="eyebrow">ملفك المهني</span><h2>{development?'تعلّم مستمر وأثر مهني':'خبرات تُشارك وممارسات تتطور'}</h2><p>{development?'وثّق الدورات والبرامج وورش العمل في سجلات مستقلة.':'وثّق كل برنامج أو لقاء لتبادل الخبرات في سجل مستقل.'} أرفق شاهدًا واحدًا على الأقل لكل نشاط، ويمكن إضافة المزيد في أي وقت.</p></div><Button disabled={busy} onClick={()=>setShowForm(v=>!v)}><Plus size={17}/>{showForm?'إغلاق النموذج':'إضافة نشاط جديد'}</Button></section>
 <div className="documentation-stats"><span><FolderOpen/>{list.length} نشاطًا مسجلًا</span><span><CheckCircle2/>{list.filter(r=>r.status==='done'&&r.files.length).length} نشاطًا موثقًا</span><span><Paperclip/>{list.reduce((n,r)=>n+r.files.length,0)} شاهدًا مرفقًا</span></div>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="success" role="status">{notice}</p>}
 {(showForm||!list.length)&&<section className="panel documentation-form"><div className="section-heading"><div><h3>{development?'إضافة دورة أو برنامج أو ورشة عمل':'إضافة برنامج لتبادل الخبرات'}</h3><p>يُضاف النشاط وشواهده إلى ملف الإنجاز، ولا يدخل ضمن نسبة الإنجاز العامة.</p></div><span className="reference-badge">شاهد مطلوب للتوثيق</span></div><form className="professional-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);setBusy(true);setError('');setNotice('');try{if(!chosen.length)throw new Error('اختر شاهدًا واحدًا على الأقل لتوثيق النشاط.');validateEvidenceFiles(chosen);const payload={title:String(f.get('title')),kind:String(f.get('kind')),date:String(f.get('date')),provider:String(f.get('provider')),notes:String(f.get('notes'))};draft.current||=crypto.randomUUID();await save(draft.current,'not_done',payload);await uploadEvidence(csrf,category,draft.current,'general',chosen);await save(draft.current,'done',payload);draft.current=null;setChosen([]);form.reset();setShowForm(false);setNotice('حُفظ النشاط مع شواهده في ملف الإنجاز. يمكنك إضافة نشاط آخر.')}catch(e){setError((e as Error).message)}finally{try{await onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}}>
 <div className="form-grid"><label>نوع النشاط<select name="kind"><option>دورة تدريبية</option><option>برنامج تدريبي</option><option>ورشة عمل</option><option>لقاء مهني</option>{!development&&<option>زيارة تبادل خبرات</option>}</select></label><label>اسم النشاط<input name="title" required minLength={3} maxLength={140} placeholder={development?'مثال: السلامة في المنشآت الكهربائية':'مثال: أساليب التدريب العملي بالمحاكاة'}/></label><label>تاريخ التنفيذ<input type="date" name="date" required/></label><label>الجهة المنظمة أو المشاركون<input name="provider" maxLength={180} placeholder="اختياري"/></label></div><label>وصف النشاط وأثره المهني<textarea name="notes" required maxLength={2500} rows={3} placeholder="أبرز ما اكتسبته أو شاركته، وأثره على ممارساتك التدريبية"/></label>
 <div className="attachment-composer"><h4><Paperclip size={18}/>شواهد النشاط</h4><EvidencePicker busy={busy} count={chosen.length} onFiles={files=>{try{validateEvidenceFiles(files);setChosen(v=>[...v,...files]);setError('')}catch(e){setError((e as Error).message)}}}/>{chosen.length>0&&<ul className="selected-files">{chosen.map((f,i)=><li key={i}><span>{f.name}</span><button type="button" disabled={busy} onClick={()=>setChosen(v=>v.filter((_,j)=>i!==j))}>إزالة من الاختيار</button></li>)}</ul>}</div><Button type="submit" disabled={busy||!chosen.length}>{busy?'جارٍ حفظ النشاط وشواهده…':'حفظ النشاط والشواهد'}</Button></form></section>}
 <div className="documentation-records">{list.map(r=><article className="documentation-record panel" key={r.id}><header><span className="module-icon"><Icon size={22}/></span><div><small>{String(r.payload.kind||'نشاط مهني')}</small><h3>{recordLabel(r)}</h3></div><span className={'tw-status '+(r.status==='done'&&r.files.length?'done':'not_done')}>{r.status==='done'&&r.files.length?'موثّق':'بانتظار الشاهد'}</span></header><div className="record-meta"><span><CalendarDays size={15}/>{String(r.payload.date||'تاريخ غير مسجل')}</span>{!!r.payload.provider&&<span>{String(r.payload.provider)}</span>}</div><p>{String(r.payload.notes||'')}</p><EvidenceFiles files={r.files}/><EvidencePicker busy={busy} count={r.files.length} onFiles={files=>void append(r,files)}/></article>)}</div>
 </div>;
}
