'use client';
import './trainer-polish.css';
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';
import {BookOpen,CalendarDays,Check,Download,FileCheck2,Bell,Users,ArrowUpLeft,Layers,Paperclip,ClipboardList} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {User} from '@/lib/contracts';
import {criteria,categoryLabels,courseCategories,recordLabel,progressFor,trainerProgress,taskAlerts,isComplete,trainingMethods,type TrainerCourse,type WorkRecord,type TrainerTask,type Criterion} from '@/lib/trainer-domain';
import GradeImport from './grade-import';
import {IndicatorRing,IndicatorChart} from './indicator-charts';
import {EvidenceFiles as Files,EvidencePicker as FilePicker,uploadEvidence} from './trainer-evidence';
import TrainerDocumentation from './trainer-documentation';
import CourseDataTable from './course-data-table';
type Workspace={courses:TrainerCourse[];records:WorkRecord[];tasks:TrainerTask[];term:string|null;linkStatus:string};
const routes:Record<string,string>={exam:'exams',grade_analysis:'grades',blackboard:'blackboard',training:'training',advising:'advising'};
const n=(v:number)=>v.toLocaleString('ar-SA-u-nu-latn');
const date=(v:string|number)=>new Date(v).toLocaleDateString('ar-SA',{timeZone:'Asia/Riyadh',year:'numeric',month:'short',day:'numeric'});
const status=(r?:WorkRecord)=>r?.status==='not_applicable'?'غير منطبق':r?.status==='done'?'منفّذ':'لم يُنفّذ';
function Progress({value,done,total}:{value:number|null;done?:number;total?:number}){return <div className="achievement-progress"><div><span>{done!==undefined?n(done)+' من '+n(total||0)+' مكتمل':'نسبة الإنجاز'}</span><b>{value===null?'—':value+'٪'}</b></div><div role="progressbar" aria-label="نسبة الإنجاز" aria-valuenow={value??undefined} aria-valuetext={value===null?'غير متاح':undefined} aria-valuemin={0} aria-valuemax={100} className="progress-track"><span style={{width:(value||0)+'%',background:value!==null&&value>=90?'#079a78':value!==null&&value>=70?'#d89516':'#d65d68'}}/></div></div>}
export default function TrainerWorkspace({user,csrf,section='overview'}:{user:User;csrf:string;section?:string}){
 const[data,setData]=useState<Workspace>({courses:[],records:[],tasks:[],term:null,linkStatus:'loading'}),[selected,setSelected]=useState(''),[courseFilter,setCourseFilter]=useState(''),[courseView,setCourseView]=useState('cards'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[now,setNow]=useState(Date.now),[profile,setProfile]=useState<{specialty?:string;staff_number?:string;office_hours?:{day:number;start:string;end:string}[]}>({});
 const refresh=useCallback(async()=>{const r=await fetch('/api/trainer/workspace',{cache:'no-store'}),d=await r.json() as Workspace & {error?:string};if(!r.ok)throw new Error(d.error);setData(d);setSelected(v=>d.courses.some((c:TrainerCourse)=>c.key===v)?v:d.courses.some((c:TrainerCourse)=>c.key===new URLSearchParams(location.search).get('section'))?new URLSearchParams(location.search).get('section')||'':'');const p=await fetch('/api/profiles/'+user.id);if(p.ok)setProfile((await p.json() as {profile:typeof profile}).profile)},[user.id]);
 useEffect(()=>{void Promise.resolve().then(refresh).catch(e=>setError(e.message));const id=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(id)},[refresh]);
 const {courses,records,tasks,term}=data,score=trainerProgress(records,courses),alerts=taskAlerts(tasks,now),course=courses.find(c=>c.key===selected);
 const category=Object.keys(routes).find(k=>routes[k]===section),scope=category&&courseCategories.has(category)?selected:'general';
 const saved=(item:Criterion)=>records.find(r=>r.course_key===scope&&r.category===item.category&&r.item_key===item.key);
 async function request(path:string,method:string,body:unknown){const r=await fetch('/api/'+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(body)}),d=await r.json() as {id:string;error?:string};if(!r.ok)throw new Error(d.error);return d}
 async function action(fn:()=>Promise<unknown>){setBusy(true);setError('');setNotice('');try{await fn();setNotice('حُفظ التحديث بنجاح.')}catch(e){setError((e as Error).message)}finally{try{await refresh()}catch(e){setError((e as Error).message)}setBusy(false)}}
 async function upload(category:string,key:string,courseKey:string,file:File){const form=new FormData();form.set('file',file);form.set('category',category);form.set('itemKey',key);form.set('courseKey',courseKey);const r=await fetch('/api/trainer/workspace/files',{method:'POST',headers:{'X-CSRF-Token':csrf},body:form}),d=await r.json() as {id:string;error?:string};if(!r.ok)throw new Error(d.error);return d}
 const save=(item:Criterion,state:string,payload?:Record<string,unknown>)=>action(()=>request('trainer/workspace/records','POST',{courseKey:scope,category:item.category,itemKey:item.key,status:state,payload:payload||saved(item)?.payload||{}}));
 function taskList(compact=false){return <div className="task-list">{(compact?tasks.slice(0,4):tasks).map(t=>{const r=records.find(r=>r.category==='assignment'&&r.item_key===t.id);return <article key={t.id}><div><span className={'tw-status '+(t.status==='done'?'done':'not_done')}>{t.status==='done'?'منجز':'قيد المتابعة'}</span><h4>{t.title}</h4><p>{t.description}</p><small>إسناد: {t.created_by_name||'رئيس القسم'} · التسليم: {date(t.due_at)}</small>{!compact&&<><div className="assignment-attachments"><h4>قرار التكليف</h4><Files files={(r?.files||[]).filter(f=>f.purpose==='decision')}/><FilePicker busy={busy} label="إرفاق قرار التكليف" onFiles={files=>void action(()=>uploadEvidence(csrf,'assignment',t.id,'general',files,'decision'))}/><h4>شواهد التنفيذ</h4><Files files={(r?.files||[]).filter(f=>f.purpose!=='decision')}/></div><div className="action-row"><Button disabled={busy} variant="outline" onClick={()=>void action(()=>request('tasks/'+t.id,'PATCH',{status:t.status==='done'?'pending':'done'}))}>{t.status==='done'?'إعادة للمتابعة':'تسجيل إنجاز المهمة'}</Button><FilePicker busy={busy} count={(r?.files||[]).filter(f=>f.purpose!=='decision').length} onFiles={files=>void action(()=>uploadEvidence(csrf,'assignment',t.id,'general',files))}/></div></>}</div></article>})}{!tasks.length&&<p className="empty-state">لا توجد مهام مسندة إليك حاليًا.</p>}</div>}
 function alertList(){return <div className="task-list">{alerts.map(t=><article className={t.overdue?'deadline-overdue':''} key={t.id}><Bell size={20}/><div><h4>{t.overdue?'تجاوز موعد التسليم':'تذكير بموعد التسليم'}</h4><p>{t.title}</p><small>{date(t.due_at)}</small><Link className="text-button" href="/trainer/assignments">عرض التكليف</Link></div></article>)}{!alerts.length&&<p className="empty-state">لا توجد تنبيهات مستحقة الآن. تظهر التذكيرات تلقائيًا قبل مواعيد المهام المسندة.</p>}</div>}
 function criterionCard(item:Criterion){const r=saved(item),done=isComplete(r,item);return <article className={'criterion-card '+(item.category==='training'?'training-card '+item.key:'')} key={item.category+item.key}><header><div><h3>{item.category==='training'&&<ClipboardList size={19}/>} {item.label}</h3><small className={item.required?'counted-label':'help'}>{item.required?'يسهم في نسبة إنجازك':'توثيق إضافي · لا يدخل في نسبة الإنجاز'}</small></div><span className={'tw-status '+(done?'done':r?.status==='not_applicable'?'not_applicable':'not_done')}>{done?'منفّذ':r?.status==='not_applicable'?'غير منطبق':'لم يُنفّذ'}</span></header>
 {item.category==='training'&&item.key==='methods'&&<div className="training-methods">{trainingMethods.map(m=><label key={m}><input type="checkbox" disabled={busy} checked={Array.isArray(r?.payload.methods)&&r.payload.methods.includes(m)} onChange={e=>{const methods=Array.isArray(r?.payload.methods)?r.payload.methods as string[]:[];void save(item,'not_done',{methods:e.target.checked?[...methods,m]:methods.filter(x=>x!==m)})}}/>{m}</label>)}</div>}
 {item.category==='grade_analysis'?<><GradeImport term={term} files={r?.files||[]} onSave={async(file,input)=>{const f=await upload(item.category,item.key,scope,file);await request('trainer/workspace/analysis','POST',{...input,fileId:f.id});await refresh()}}/>{r?.payload.analysisVersion===2?<div className="grade-result"><div className="grade-numbers">{[['المتوسط',r.payload.average],['الأعلى',r.payload.max],['الأدنى',r.payload.min],['نسبة النجاح',r.payload.passRate+'٪']].map(([label,value])=><span key={String(label)}>{String(label)}<b>{String(value)}</b></span>)}</div><small>عدد الدرجات: {String(r.payload.count)} · الدرجة العظمى: {String(r.payload.maximum)}</small><IndicatorChart title="توزيع درجات المتدربين" labels={(r.payload.distribution as {label:string;count:number}[]).map(b=>b.label)} series={[{label:'عدد الدرجات',values:(r.payload.distribution as {label:string;count:number}[]).map(b=>b.count)}]} horizontal height={220}/><p>{(r.payload.recommendations as string[]).join(' ')}</p></div>:r&&<p className="warning">يلزم إعادة تحليل الملف بعد التحقق من ورقة العمل وعمود الدرجات قبل احتساب هذا البند.</p>}</>:<><p className="help">{item.witness?'أرفق الشاهد أولًا، ثم حدّد حالة التنفيذ.':'حدّد حالة التنفيذ، ويمكنك إرفاق شاهد للتوثيق.'}</p><FilePicker busy={busy} count={r?.files.length||0} onFiles={files=>void action(()=>uploadEvidence(csrf,item.category,item.key,scope,files))}/></>}
 <Files files={r?.files||[]}/>{item.category!=='grade_analysis'&&r?.status!=='not_applicable'&&<div className="action-row"><Button disabled={busy||(item.witness&&!r?.files.length)||(item.category==='training'&&item.key==='methods'&&!(r?.payload.methods as string[]|undefined)?.length)} variant={done?'default':'outline'} onClick={()=>void save(item,'done')}><Check size={15}/>منفّذ</Button><Button disabled={busy} variant={r?.status==='not_done'?'default':'outline'} onClick={()=>void save(item,'not_done')}>لم يُنفّذ</Button></div>}</article>}
 function documentation(){return <TrainerDocumentation key={section} category={section as 'development'|'exchange'} records={records} csrf={csrf} onSaved={refresh}/>}
 const legacy=records.filter(r=>courseCategories.has(r.category)&&!courses.some(c=>c.key===r.course_key));
 async function downloadPortfolio(){setBusy(true);setError('');try{const r=await fetch('/api/trainer/workspace/portfolio');if(!r.ok)throw new Error((await r.json() as {error:string}).error);const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='ملف الإنجاز - '+user.display_name+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="trainer-v2" dir="rtl">{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success">{notice}</p>}
 {section==='overview'&&<><section className="trainer-hero"><div><span className="eyebrow">قسم التقنية الكهربائية · الفصل {term||'الحالي'}</span><h2>مرحبًا، {user.display_name}</h2><p>منجزاتك التدريبية ومؤشرات تقدمك في مكان واحد.</p><Link href="/trainer/portfolio">عرض ملف الإنجاز <ArrowUpLeft size={17}/></Link></div><IndicatorRing value={score.percent}/></section><div className="trainer-summary">{[['المقررات',new Set(courses.map(c=>c.code)).size],['الشعب المسندة',courses.length],['الشواهد المرفقة',records.reduce((n,r)=>n+r.files.length,0)]].map(([label,value])=><article key={String(label)}><span className="pi-card-icon">{label==='المقررات'?<BookOpen/>:label==='الشعب المسندة'?<Layers/>:<Paperclip/>}</span><div><span>{label}</span><b>{value}</b></div></article>)}</div><div className="section-heading"><div><h3>مؤشرات إنجازك</h3><p>متوسط المعايير المنطبقة؛ يُحسب كل معيار تدريبي على مستوى الشعب ثم يُجمع في المؤشر العام.</p></div></div><div className="achievement-grid">{score.categories.map(c=><a href={'/trainer/'+routes[c.category]} className="achievement-card" key={c.category}><div className="pi-card-heading"><FileCheck2/><h3>{categoryLabels[c.category]}</h3></div><IndicatorRing value={c.percent} label="نسبة الإنجاز" small/><Progress value={c.percent} done={c.done} total={c.total}/></a>)}</div><section className="panel analytics-panel"><div className="section-heading"><div><h3>مقارنة مؤشرات الإنجاز</h3><p>النسب نفسها المعروضة في بطاقات المعايير.</p></div></div><IndicatorChart title="مقارنة مؤشرات الإنجاز" labels={score.categories.map(c=>categoryLabels[c.category])} series={[{label:'نسبة الإنجاز',values:score.categories.map(c=>c.percent)}]} percent horizontal/></section><div className="dashboard-columns"><section className="panel"><div className="section-heading"><h3><CalendarDays/>المهام المسندة من رئيس القسم</h3><Link href="/trainer/assignments">عرض الجميع</Link></div>{taskList(true)}</section><section className="panel"><div className="section-heading"><h3><Bell/>التنبيهات</h3><Link href="/trainer/alerts">عرض الجميع</Link></div>{alertList()}</section></div></>}
 {section==='courses'&&<><div className="section-heading"><div><h3>مقرراتك وشعبك التدريبية</h3><p>لكل شعبة رقم مرجعي مستقل، ولو تكرر اسم المقرر. حالات المتدربين مستمدة من SF01.</p></div><span className="reference-badge">{courses.length} شعبة</span></div><section className="panel course-toolbar"><label>تصفية المقررات والشعب<select aria-label="تصفية المقررات والشعب" value={courseFilter} onChange={e=>setCourseFilter(e.target.value)}><option value="">جميع المقررات والشعب</option>{courses.map(c=><option key={c.key} value={c.key}>{c.name} — الرقم المرجعي {c.reference}</option>)}</select></label><div className="view-switch"><button aria-pressed={courseView==='cards'} onClick={()=>setCourseView('cards')}>بطاقات</button><button aria-pressed={courseView==='table'} onClick={()=>setCourseView('table')}>جدول البيانات</button></div></section>{courseView==='table'?<section className="panel analytics-panel"><CourseDataTable courses={courses.filter(c=>!courseFilter||c.key===courseFilter)} records={records}/></section>:<div className="course-catalog">{courses.filter(c=>!courseFilter||c.key===courseFilter).map(c=><article className="course-card" key={c.key}><header><BookOpen/><span className="reference-badge">الرقم المرجعي {c.reference}</span></header><h3>{c.name}</h3><p className="help">{c.code} · {c.sectionType}</p><div className="course-total"><Users/><b>{c.trainees}</b><span>متدربًا في الشعبة</span></div><div className="course-risk">{[['المحرومون',c.deprived],['المنسحبون',c.withdrawn],['مطوي القيد',c.dismissed]].map(([label,count])=><div key={String(label)}><span>{label}</span><b>{count}</b><small>{c.trainees?(Number(count)*100/c.trainees).toFixed(1):'0'}٪</small></div>)}</div><Progress value={progressFor(records,c.key).percent}/><a className="course-link" href={'/trainer/exams?section='+encodeURIComponent(c.key)}>متابعة متطلبات الشعبة <ArrowUpLeft size={16}/></a></article>)}</div>}<p className="help">نسبة كل حالة من إجمالي متدربي الشعبة. قد تتداخل الحالات ولا تُجمع نسبها.</p></>}
 {category&&<><div className="section-heading"><div><h3>{categoryLabels[category]}</h3><p>{category==='advising'?'تابع ممارساتك الإرشادية وسجّل ما أنجزته لدعم المتدربين.':'اختر المقرر والشعبة لتوثيق التنفيذ واحتساب الإنجاز بدقة.'}</p></div></div>{courseCategories.has(category)&&<section className="panel section-picker"><label htmlFor="section-picker">المقرر والشعبة التدريبية</label><select id="section-picker" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">اختر اسم المقرر والرقم المرجعي</option>{courses.map(c=><option value={c.key} key={c.key}>{c.name} — الرقم المرجعي {c.reference}</option>)}</select></section>}
 {legacy.filter(r=>r.category===category).length>0&&<details className="legacy-records"><summary>سجلات سابقة تحتاج تحديد الشعبة ({legacy.filter(r=>r.category===category).length})</summary><p>حُفظت هذه السجلات دون رقم مرجعي. حدّد شعبتها لتظهر ضمن إنجازك دون تكرار الشواهد.</p>{legacy.filter(r=>r.category===category).map(r=><div key={r.id}><b>{recordLabel(r)}</b><Files files={r.files}/><select defaultValue="" disabled={busy} aria-label={'ربط '+recordLabel(r)} onChange={e=>{const courseKey=e.target.value;if(courseKey)void action(()=>request('trainer/workspace/records/'+r.id+'/scope','PATCH',{courseKey}))}}><option value="">حدد الشعبة التابعة لهذا السجل</option>{courses.map(c=><option key={c.key} value={c.key}>{c.name} — {c.reference}</option>)}</select></div>)}</details>}
 {(!courseCategories.has(category)||course)&&<><section className="criterion-summary panel"><div><span className="eyebrow">متابعة التنفيذ</span><h3>{scope==='general'?'الإرشاد الأكاديمي العام للمدرب':course?.name}</h3>{scope!=='general'&&course&&<p>الرقم المرجعي {course.reference}</p>}<Progress {...(()=>{const p=progressFor(records,scope,category);return {value:p.percent,done:p.done,total:p.total}})()}/></div><IndicatorRing value={progressFor(records,scope,category).percent} label="إنجاز المعيار" small/></section>{category==='grade_analysis'&&<CombinedGrades records={records.filter(r=>r.course_key===scope&&r.category==='grade_analysis'&&r.payload.analysisVersion===2&&r.status==='done')}/>}<div className={'criterion-grid '+(category==='training'?'training-grid':'')}>{criteria.filter(c=>c.category===category).map(criterionCard)}</div></>}
 {category==='training'&&!course&&<div className="training-preview">{criteria.filter(c=>c.category==='training').map(c=><article key={c.key}><span className="module-icon"><ClipboardList/></span><h3>{c.label}</h3><p>{c.key==='methods'?'١١ أسلوبًا تدريبيًا لتوثيق ممارساتك في الشعبة.':c.key==='assignments'?'توثيق الواجبات مع شواهد التنفيذ.':'توثيق إضافي للممارسات التدريبية.'}</p><small>{c.required?'يسهم في نسبة إنجازك':'توثيق إضافي'}</small></article>)}<p className="help">اختر الشعبة من القائمة لبدء التوثيق.</p></div>}
 </>}
 {(section==='development'||section==='exchange')&&documentation()}
 {section==='assignments'&&<section className="panel"><div className="section-heading"><div><h3>التكليفات المسندة إليك</h3><p>مهام ينشئها رئيس القسم. سجّل إنجازها وأرفق ما يدعم التنفيذ.</p></div></div>{taskList()}</section>}
 {section==='alerts'&&<div className="dashboard-columns"><section className="panel"><div className="section-heading"><h3><Bell/>التنبيهات التلقائية</h3></div>{alertList()}</section><section className="panel"><div className="section-heading"><h3><CalendarDays/>المواعيد القادمة</h3></div><div className="task-list">{tasks.filter(t=>t.status!=='done'&&Date.parse(t.due_at)>=now).sort((a,b)=>Date.parse(a.due_at)-Date.parse(b.due_at)).map(t=><article key={t.id}><div><b>{t.title}</b><p>{date(t.due_at)}</p><small>يظهر التذكير قبل الموعد بـ {t.reminder_days} أيام.</small></div></article>)}{!tasks.some(t=>t.status!=='done'&&Date.parse(t.due_at)>=now)&&<p className="empty-state">لا توجد مواعيد قادمة مسندة إليك.</p>}</div></section></div>}
 {section==='portfolio'&&<section className="portfolio-view panel"><div className="section-heading no-print"><div><h3>ملف الإنجاز المتكامل</h3><p>بياناتك ومؤشراتك وسجلاتك وشواهدك في ملف واحد قابل للتنزيل.</p></div><div className="action-row"><Button disabled={busy} onClick={()=>void downloadPortfolio()}><Download size={16}/>تنزيل الملف مع الشواهد</Button><Button variant="outline" onClick={()=>window.print()}>طباعة الملخص</Button></div></div><div className="portfolio-cover"><div><p>قسم التقنية الكهربائية</p><h2>ملف الإنجاز المهني والتدريبي</h2><h3>{user.display_name}</h3><p>الرقم الوظيفي: {profile.staff_number||user.staff_number||'—'} · اسم المستخدم: {user.username}</p><p>التخصص: {profile.specialty||'لم يُحدد'} · الفصل: {term}</p></div><IndicatorRing value={score.percent}/></div><p className="help">يحتوي الملف المنزّل على جميع المرفقات الأصلية. الصور تظهر ضمن الطباعة؛ بقية الصيغ تُنزّل من داخل الملف وتُطبع عبر تطبيقاتها.</p><div className="achievement-grid">{score.categories.map(c=><div key={c.category}><h3>{categoryLabels[c.category]}</h3><Progress value={c.percent} done={c.done} total={c.total}/></div>)}</div><h3>ملخص المقررات والشعب</h3><CourseDataTable courses={courses} records={records}/><h3>سجل المعايير والشواهد</h3>{records.map(r=><article className="portfolio-entry" key={r.id}><div><small>{categoryLabels[r.category]} · {courses.find(c=>c.key===r.course_key)?.name||'سجل المدرب'} {courses.find(c=>c.key===r.course_key)?.reference||''}</small><h4>{recordLabel(r)}</h4><p>{String(r.payload.notes||'')}</p></div><span className="tw-status">{status(r)}</span><Files files={r.files}/></article>)}{!records.length&&<p className="empty-state">يظهر كل سجل وشاهد هنا تلقائيًا عند توثيقه.</p>}<h3>التكليفات</h3>{taskList(true)}</section>}
 {data.linkStatus!=='ready'&&['courses','exams','grades','blackboard','training'].includes(section)&&<p className="empty-state">{data.linkStatus==='loading'?'جارٍ تحميل الشعب…':data.linkStatus==='no_assigned_sections'?'لا توجد شعب مسندة إلى رقمك الوظيفي في تقرير الفصل الحالي.':'تعذر عرض الشعب. تحقق من اكتمال تقريري SF01 وSS01 للفصل نفسه وربط الرقم الوظيفي بالحساب.'}</p>}
 </div>;
}
function CombinedGrades({records}:{records:WorkRecord[]}){const count=records.reduce((n,r)=>n+Number(r.payload.count),0),average=count?records.reduce((n,r)=>n+Number(r.payload.averagePercent)*Number(r.payload.count),0)/count:null,pass=count?records.reduce((n,r)=>n+Number(r.payload.passed),0)*100/count:null;return <section className="combined-grades panel"><h3>المؤشر الشامل لتحليل الدرجات</h3><div className="grade-numbers"><span>الملفات المعتمدة<b>{records.length}</b></span><span>المتوسط النسبي الموزون<b>{average===null?'—':average.toFixed(1)+'٪'}</b></span><span>نسبة النجاح الموزونة<b>{pass===null?'—':pass.toFixed(1)+'٪'}</b></span></div>{records.length>0&&<IndicatorChart title="متوسط نتائج ملفات التقييم" type="line" percent labels={records.map(r=>recordLabel(r))} series={[{label:'المتوسط النسبي',values:records.map(r=>Number(r.payload.averagePercent))}]}/>}<p className="help">تُحوّل الدرجات إلى نسبة من الدرجة العظمى لكل ملف، ثم تُوزن بعدد درجاته المعتمدة. هذا المؤشر لا يمثل المجموع النهائي لدرجات المتدرب.</p></section>}
