'use client';
import TrainingMethods from './training-methods';
import {validatePortfolioDownload} from '@/lib/portfolio-contract';
import Link from 'next/link';
import {useCallback,useEffect,useState,useRef} from 'react';
import {BookOpen,CalendarDays,Check,Download,FileCheck2,Bell,Users,ArrowUpLeft,Layers,Paperclip,ClipboardList} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {User} from '@/lib/contracts';
import {criteria,categoryLabels,courseCategories,recordLabel,progressFor,trainerProgress,taskAlerts,isComplete,trainingMethods,type TrainerCourse,type WorkRecord,type TrainerTask,type Criterion} from '@/lib/trainer-domain';
import GradeImport from './grade-import';
import {IndicatorRing,IndicatorChart} from './indicator-charts';
import {EvidenceFiles as Files,EvidenceUploader,uploadEvidence} from './trainer-evidence';
import TrainerDocumentation from './trainer-documentation';
import CourseDataTable from './course-data-table';
type Workspace={upcomingTasks?:TrainerTask[];nextCursor?:string|null;total?:number;tasksNextCursor?:string|null;tasksTotal?:number;summary?:{score:ReturnType<typeof trainerProgress>;courseProgress:Record<string,ReturnType<typeof progressFor>>;attachments:number};courses:TrainerCourse[];records:WorkRecord[];tasks:TrainerTask[];term:string|null;linkStatus:string};
const routes:Record<string,string>={exam:'exams',grade_analysis:'grades',blackboard:'blackboard',training:'training',advising:'advising'};
const n=(v:number)=>v.toLocaleString('ar-SA-u-nu-latn');
const date=(v:string|number)=>new Date(v).toLocaleString('ar-SA',{timeZone:'Asia/Riyadh',dateStyle:'medium',timeStyle:'short'});
const status=(r?:WorkRecord)=>r?.status==='not_applicable'?'غير منطبق':r?.status==='done'?'منفّذ':'لم يُنفّذ';
function Progress({value,done,total,label='إنجاز الشعبة'}:{value:number|null;done?:number;total?:number;label?:string}){return <div className="achievement-progress"><div><span>{label}{done!==undefined?' · '+n(done)+' / '+n(total||0)+' بند':''}</span><b>{value===null?'—':value+'٪'}</b></div><div role="progressbar" aria-label={label} aria-valuenow={value??undefined} aria-valuetext={value===null?'غير متاح':undefined} aria-valuemin={0} aria-valuemax={100} className="progress-track"><span style={{width:(value||0)+'%',background:value!==null&&value>=90?'#079a78':value!==null&&value>=70?'#d89516':'#d65d68'}}/></div></div>}
export default function TrainerWorkspace({user,csrf,section='overview'}:{user:User;csrf:string;section?:string}){
 const[data,setData]=useState<Workspace>({courses:[],records:[],tasks:[],term:null,linkStatus:'loading'}),[selected,setSelected]=useState(''),[courseFilter,setCourseFilter]=useState(''),[courseView,setCourseView]=useState('cards'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[now,setNow]=useState(Date.now),[profile,setProfile]=useState<{specialty?:string;staff_number?:string;office_hours?:{day:number;start:string;end:string}[]}>({});
 const[loaded,setLoaded]=useState(false),[loadError,setLoadError]=useState(''),[methodsDirty,setMethodsDirty]=useState(false),[advisingFilter,setAdvisingFilter]=useState('all');
 const generation=useRef(0);const workspaceUrl=useCallback(()=>{const p=new URLSearchParams({view:section,section:selected});const task=new URLSearchParams(location.search).get('task');if(task&&section==='assignments')p.set('task',task);return '/api/trainer/workspace?'+p},[section,selected]);
 const refresh=useCallback(async()=>{const version=++generation.current;setLoadError('');try{const r=await fetch(workspaceUrl(),{cache:'no-store'}),d=await r.json() as Workspace & {error?:string};if(!r.ok)throw new Error(d.error);if(version!==generation.current)return;setData(d);setLoaded(true);setSelected(v=>d.courses.some((c:TrainerCourse)=>c.key===v)?v:d.courses.some((c:TrainerCourse)=>c.key===new URLSearchParams(location.search).get('section'))?new URLSearchParams(location.search).get('section')||'':'');const p=await fetch('/api/profiles/'+user.id);if(p.ok){const nextProfile=(await p.json() as {profile:typeof profile}).profile;if(version===generation.current)setProfile(nextProfile)}}catch(e){if(version===generation.current)setLoadError((e as Error).message);throw e}},[user.id,workspaceUrl]);
 useEffect(()=>{setLoaded(false);void Promise.resolve().then(refresh).catch(()=>{});const id=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(id)},[refresh]);
 useEffect(()=>{const update=()=>{const key=new URLSearchParams(location.search).get('section');if(key)setSelected(key)};update();window.addEventListener('popstate',update);return()=>window.removeEventListener('popstate',update)},[section]);
 useEffect(()=>setMethodsDirty(false),[selected]);
 function selectCourse(key:string){setSelected(key);const url=new URL(location.href);if(key)url.searchParams.set('section',key);else url.searchParams.delete('section');history.replaceState(history.state,'',url);window.dispatchEvent(new CustomEvent('department-section-change',{detail:key}))}
 const {courses,records,tasks,term}=data,upcoming=data.upcomingTasks||[],score=data.summary?.score||trainerProgress(records,courses),alerts=taskAlerts(tasks,now),course=courses.find(c=>c.key===selected);
 const category=Object.keys(routes).find(k=>routes[k]===section),scope=category&&courseCategories.has(category)?selected:'general';
 const saved=(item:Criterion)=>records.find(r=>r.course_key===scope&&r.category===item.category&&r.item_key===item.key);
 async function request(path:string,method:string,body:unknown){const r=await fetch('/api/'+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(body)}),d=await r.json() as {id:string;error?:string};if(!r.ok)throw new Error(d.error);return d}
 async function action(fn:()=>Promise<unknown>){setBusy(true);setError('');setNotice('');try{await fn();setNotice('حُفظ التحديث بنجاح.')}catch(e){setError((e as Error).message)}finally{try{await refresh()}catch(e){setError((e as Error).message)}setBusy(false)}}
 async function upload(category:string,key:string,courseKey:string,file:File){return (await uploadEvidence(csrf,category,key,courseKey,[file]))[0]}
 async function more(kind:'records'|'tasks',all=false){setBusy(true);setError('');try{let cursor=kind==='records'?data.nextCursor:data.tasksNextCursor;const extra:Workspace[]=[];while(cursor){const response=await fetch(workspaceUrl()+'&'+(kind==='records'?'cursor':'taskCursor')+'='+encodeURIComponent(cursor)),result=await response.json() as Workspace&{error?:string};if(!response.ok)throw new Error(result.error);extra.push(result);cursor=kind==='records'?result.nextCursor:result.tasksNextCursor;if(!all)break}setData(previous=>{const items=kind==='records'?extra.flatMap(d=>d.records):extra.flatMap(d=>d.tasks);return kind==='records'?{...previous,records:[...previous.records,...(items as WorkRecord[]).filter(r=>!previous.records.some(p=>p.id===r.id))],nextCursor:cursor}:{...previous,tasks:[...previous.tasks,...(items as TrainerTask[]).filter(t=>!previous.tasks.some(p=>p.id===t.id))],records:[...previous.records,...extra.flatMap(d=>d.records).filter(r=>!previous.records.some(p=>p.id===r.id))],tasksNextCursor:cursor}})}catch(error){setError((error as Error).message);throw error}finally{setBusy(false)}}
 async function printSummary(){setBusy(true);setError('');try{const firstResponse=await fetch(workspaceUrl()),first=await firstResponse.json() as Workspace&{error?:string};if(!firstResponse.ok)throw new Error(first.error);let allRecords=[...first.records],allTasks=[...first.tasks],recordCursor=first.nextCursor,taskCursor=first.tasksNextCursor;while(recordCursor){const r=await fetch(workspaceUrl()+'&cursor='+encodeURIComponent(recordCursor)),d=await r.json() as Workspace&{error?:string};if(!r.ok)throw new Error(d.error);allRecords.push(...d.records);recordCursor=d.nextCursor}while(taskCursor){const r=await fetch(workspaceUrl()+'&taskCursor='+encodeURIComponent(taskCursor)),d=await r.json() as Workspace&{error?:string};if(!r.ok)throw new Error(d.error);allTasks.push(...d.tasks);taskCursor=d.tasksNextCursor}for(const record of allRecords){let cursor=record.filesNextCursor;while(cursor){const r=await fetch('/api/trainer/workspace/records/'+record.id+'/files?cursor='+encodeURIComponent(cursor)),d=await r.json() as {files:WorkRecord['files'];nextCursor:string|null;error?:string};if(!r.ok)throw new Error(d.error);record.files.push(...d.files.filter(f=>!record.files.some(p=>p.id===f.id)));cursor=d.nextCursor}record.filesNextCursor=null}setData({...first,records:allRecords,tasks:allTasks,nextCursor:null,tasksNextCursor:null});await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));window.print()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const save=(item:Criterion,state:string,payload?:Record<string,unknown>)=>action(()=>request('trainer/workspace/records','POST',{courseKey:scope,category:item.category,itemKey:item.key,status:state,payload:payload||saved(item)?.payload||{}}));
 function taskList(compact=false,readOnly=compact){return <div className="task-list">{(compact?tasks.slice(0,4):tasks).map(t=>{const r=records.find(r=>r.category==='assignment'&&r.item_key===t.id);return <article key={t.id} id={'task-'+t.id} tabIndex={-1}><div><span className={'tw-status '+(t.status==='done'?'done':'not_done')}>{t.status==='done'?'منجز':'قيد المتابعة'}</span><h4>{t.title}</h4><p>{t.description}</p><small>إسناد: {t.created_by_name||'رئيس القسم'} · التسليم: {date(t.due_at)}</small>{!readOnly&&<><div className="assignment-attachments"><h4>قرار التكليف</h4><Files key={r?.id+'decision'} files={r?.files||[]} recordId={r?.id} nextCursor={r?.filesNextCursor} purpose="decision"/><EvidenceUploader key={t.id+'decision'} disabled={busy} label="اختيار قرار التكليف" csrf={csrf} category="assignment" itemKey={t.id} courseKey="general" purpose="decision" onSaved={refresh}/><h4>شواهد التنفيذ</h4><Files key={r?.id+'evidence'} files={r?.files||[]} recordId={r?.id} nextCursor={r?.filesNextCursor} purpose="evidence"/></div><div className="action-row"><Button disabled={busy} variant="outline" onClick={()=>void action(()=>request('tasks/'+t.id,'PATCH',{status:t.status==='done'?'pending':'done'}))}>{t.status==='done'?'إعادة للمتابعة':'تسجيل إنجاز المهمة'}</Button><EvidenceUploader key={t.id+'evidence'} disabled={busy} csrf={csrf} category="assignment" itemKey={t.id} courseKey="general" onSaved={refresh}/></div></>}</div></article>})}{!tasks.length&&<p className="empty-state">لا توجد مهام مسندة إليك حاليًا.</p>}</div>}
 function alertList(){return <div className="task-list">{alerts.map(t=><article className={t.overdue?'deadline-overdue':''} key={t.id}><Bell size={20}/><div><h4>{t.overdue?'تجاوز موعد التسليم':'تذكير بموعد التسليم'}</h4><p>{t.title}</p><small>{date(t.due_at)}</small><Link className="text-button" href={'/trainer/assignments?task='+encodeURIComponent(t.id)}>عرض التكليف</Link></div></article>)}{!alerts.length&&<p className="empty-state">لا توجد تنبيهات مستحقة الآن. تظهر التذكيرات تلقائيًا قبل مواعيد المهام المسندة.</p>}</div>}
 function criterionCard(item:Criterion){const r=saved(item),done=isComplete(r,item);return <article className={'criterion-card '+(item.category==='training'?'training-card '+item.key:'')} key={item.category+item.key}><header><div><h3>{item.category==='training'&&<ClipboardList size={19}/>} {item.label}</h3><small className={item.required?'counted-label':'help'}>{item.required?'يسهم في نسبة إنجازك':'توثيق إضافي · لا يدخل في نسبة الإنجاز'}</small></div><span className={'tw-status '+(done?'done':r?.status==='not_applicable'?'not_applicable':'not_done')}>{done?'منفّذ':r?.status==='not_applicable'?'غير منطبق':'لم يُنفّذ'}</span></header>
 {item.category==='training'&&item.key==='methods'&&<TrainingMethods key={scope} saved={Array.isArray(r?.payload.methods)?r.payload.methods as string[]:[]} busy={busy} onDirty={setMethodsDirty} onSave={async methods=>{await request('trainer/workspace/records','POST',{courseKey:scope,category:item.category,itemKey:item.key,status:'not_done',payload:{methods}});await refresh()}}/>}
 {item.category==='grade_analysis'?<><GradeImport key={scope+':'+item.key} term={term} files={r?.files||[]} onSave={async(file,input)=>{const f=await upload(item.category,item.key,scope,file);const {scores,excluded,...selection}=input;await request('trainer/workspace/analysis','POST',{...selection,fileId:f.id});await refresh()}}/>{r?.payload.analysisVersion===2?<div className="grade-result"><div className="grade-numbers">{[['المتوسط',r.payload.average],['الأعلى',r.payload.max],['الأدنى',r.payload.min],['النجاح بين الدرجات الرقمية',r.payload.passRate+'٪']].map(([label,value])=><span key={String(label)}>{String(label)}<b>{String(value)}</b></span>)}</div><small>الدرجات المعتمدة: {String(r.payload.count)} · المستبعدة: {String(r.payload.excluded)} · الدرجة العظمى: {String(r.payload.maximum)}</small><IndicatorChart title="توزيع درجات المتدربين" labels={(r.payload.distribution as {label:string;count:number}[]).map(b=>b.label)} series={[{label:'عدد الدرجات',values:(r.payload.distribution as {label:string;count:number}[]).map(b=>b.count)}]} horizontal height={220}/><p><b>اقتراحات عامة للمراجعة: </b>{(r.payload.recommendations as string[]).join(' ')}</p></div>:r&&<p className="warning">يلزم إعادة تحليل الملف بعد التحقق من ورقة العمل وعمود الدرجات قبل احتساب هذا البند.</p>}</>:<><p className="help">{item.witness?'أرفق الشاهد أولًا، ثم حدّد حالة التنفيذ.':'حدّد حالة التنفيذ، ويمكنك إرفاق شاهد للتوثيق.'}</p><EvidenceUploader key={scope+':'+item.key} disabled={busy} csrf={csrf} category={item.category} itemKey={item.key} courseKey={scope} onSaved={refresh}/></>}
 <Files key={r?.id} files={r?.files||[]} recordId={r?.id} nextCursor={r?.filesNextCursor}/>{item.category!=='grade_analysis'&&r?.status!=='not_applicable'&&<div className="action-row"><Button disabled={busy||(item.key==='methods'&&methodsDirty)||(item.witness&&!r?.files.length)||(item.category==='training'&&item.key==='methods'&&!(r?.payload.methods as string[]|undefined)?.length)} variant={done?'default':'outline'} onClick={()=>void save(item,'done')}><Check size={15}/>منفّذ</Button><Button disabled={busy} variant={r?.status==='not_done'?'default':'outline'} onClick={()=>void save(item,'not_done')}>لم يُنفّذ</Button></div>}</article>}
 function documentation(){return <TrainerDocumentation key={section} category={section as 'development'|'exchange'} records={records} csrf={csrf} onSaved={refresh}/>}
 const legacy=records.filter(r=>courseCategories.has(r.category)&&!courses.some(c=>c.key===r.course_key));
 async function downloadPortfolio(){setBusy(true);setError('');try{const r=await fetch('/api/trainer/workspace/portfolio');if(!r.ok)throw new Error((await r.json() as {error:string}).error);const url=URL.createObjectURL(await validatePortfolioDownload(await r.blob())),a=document.createElement('a');a.href=url;a.download='ملف الإنجاز - '+user.display_name+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{if(!loaded||section!=='assignments')return;const id=new URLSearchParams(location.search).get('task');if(!id)return;const frame=requestAnimationFrame(()=>{const target=document.getElementById('task-'+id);target?.scrollIntoView({block:'center'});target?.focus({preventScroll:true})});return()=>cancelAnimationFrame(frame)},[loaded,section,data.tasks]);
 if(!loaded)return <section className="panel route-loading" aria-busy={!loadError}>{loadError?<><p role="alert">{loadError}</p><Button variant="outline" onClick={()=>void refresh().catch(()=>{})}>إعادة المحاولة</Button></>:<p role="status">جارٍ تحميل شعبك ومؤشرات إنجازك…</p>}</section>;
 return <div className="trainer-v2" dir="rtl">{loadError&&<p className="error" role="alert">تعذر تحديث البيانات، المعروض هو آخر قراءة ناجحة. <Button variant="outline" onClick={()=>void refresh().catch(()=>{})}>إعادة المحاولة</Button></p>}{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success">{notice}</p>}
 {section==='overview'&&<><section className="trainer-hero"><div><span className="eyebrow">قسم التقنية الكهربائية · الفصل {term||'الحالي'}</span><h2>مرحبًا، {user.display_name}</h2><p>منجزاتك التدريبية ومؤشرات تقدمك في مكان واحد.</p><Link href="/trainer/portfolio">عرض ملف الإنجاز <ArrowUpLeft size={17}/></Link></div><IndicatorRing value={score.percent}/></section><div className="trainer-summary">{[['المقررات',new Set(courses.map(c=>c.code)).size],['الشعب المسندة',courses.length],['الشواهد المرفقة',data.summary?.attachments??records.reduce((n,r)=>n+r.files.length,0)]].map(([label,value])=><article key={String(label)}><span className="pi-card-icon">{label==='المقررات'?<BookOpen/>:label==='الشعب المسندة'?<Layers/>:<Paperclip/>}</span><div><span>{label}</span><b>{value}</b></div></article>)}</div><div className="section-heading"><div><h3>مؤشرات إنجازك</h3><p>متوسط المعايير المنطبقة؛ يُحسب كل معيار تدريبي على مستوى الشعب ثم يُجمع في المؤشر العام.</p></div></div><div className="achievement-grid">{score.categories.map(c=><a href={'/trainer/'+routes[c.category]+(c.category!=='advising'&&selected?'?section='+encodeURIComponent(selected):'')} className="achievement-card" key={c.category}><div className="pi-card-heading"><FileCheck2/><h3>{categoryLabels[c.category]}</h3></div><IndicatorRing value={c.percent} label="نسبة الإنجاز" small/><Progress value={c.percent} done={c.done} total={c.total} label={c.category==='advising'?'إنجاز ممارسات الإرشاد':'متوسط إنجاز الشعب: '+categoryLabels[c.category]}/></a>)}</div><section className="panel analytics-panel"><div className="section-heading"><div><h3>مقارنة مؤشرات الإنجاز</h3><p>النسب نفسها المعروضة في بطاقات المعايير.</p></div></div><IndicatorChart title="مقارنة مؤشرات الإنجاز" labels={score.categories.map(c=>categoryLabels[c.category])} series={[{label:'نسبة الإنجاز',values:score.categories.map(c=>c.percent)}]} percent horizontal/></section><div className="dashboard-columns"><section className="panel"><div className="section-heading"><h3><CalendarDays/>المهام المسندة من رئيس القسم</h3><Link href="/trainer/assignments">عرض الجميع</Link></div>{taskList(true)}</section><section className="panel"><div className="section-heading"><h3><Bell/>التنبيهات</h3><Link href="/trainer/alerts">عرض الجميع</Link></div>{alertList()}</section></div></>}
 {section==='courses'&&<><div className="section-heading"><div><h3>مقرراتك وشعبك التدريبية</h3><p>لكل شعبة رقم مرجعي مستقل، ولو تكرر اسم المقرر. حالات المتدربين مستمدة من SF01.</p></div><span className="reference-badge">{courses.length} شعبة</span></div><section className="panel course-toolbar"><label>تصفية المقررات والشعب<select aria-label="تصفية المقررات والشعب" value={courseFilter} onChange={e=>setCourseFilter(e.target.value)}><option value="">جميع المقررات والشعب</option>{courses.map(c=><option key={c.key} value={c.key}>{c.name} — الرقم المرجعي {c.reference}</option>)}</select></label><div className="view-switch"><button aria-pressed={courseView==='cards'} onClick={()=>setCourseView('cards')}>بطاقات</button><button aria-pressed={courseView==='table'} onClick={()=>setCourseView('table')}>جدول البيانات</button></div></section>{courseView==='table'?<section className="panel analytics-panel"><CourseDataTable courses={courses.filter(c=>!courseFilter||c.key===courseFilter)} records={records} progress={data.summary?.courseProgress}/></section>:<div className="course-catalog">{courses.filter(c=>!courseFilter||c.key===courseFilter).map(c=><article className="course-card" key={c.key}><header><BookOpen/><span className="reference-badge">الرقم المرجعي {c.reference}</span></header><h3>{c.name}</h3><p className="help">{c.code} · {c.sectionType}</p><div className="course-total"><Users/><b>{c.trainees}</b><span>متدربًا في الشعبة</span></div><div className="course-risk">{[['المحرومون',c.deprived],['المنسحبون',c.withdrawn],['مطوي القيد',c.dismissed]].map(([label,count])=><div key={String(label)}><span>{label}</span><b>{count}</b><small>{c.trainees?(Number(count)*100/c.trainees).toFixed(1):'0'}٪</small></div>)}</div><Progress value={data.summary?.courseProgress[c.key]?.percent??progressFor(records,c.key).percent}/><a className="course-link" href={'/trainer/exams?section='+encodeURIComponent(c.key)}>متابعة متطلبات الشعبة <ArrowUpLeft size={16}/></a></article>)}</div>}<p className="help">نسبة كل حالة من إجمالي متدربي الشعبة. قد تتداخل الحالات ولا تُجمع نسبها.</p></>}
 {category&&<><div className="section-heading"><div><h3>{categoryLabels[category]}</h3><p>{category==='advising'?'تابع ممارساتك الإرشادية وسجّل ما أنجزته لدعم المتدربين.':'اختر المقرر والشعبة لتوثيق التنفيذ واحتساب الإنجاز بدقة.'}</p></div></div>{courseCategories.has(category)&&<section className="panel section-picker"><label htmlFor="section-picker">المقرر والشعبة التدريبية</label><select id="section-picker" value={selected} onChange={e=>selectCourse(e.target.value)}><option value="">اختر اسم المقرر والرقم المرجعي</option>{courses.map(c=><option value={c.key} key={c.key}>{c.name} — الرقم المرجعي {c.reference}</option>)}</select></section>}
 {legacy.filter(r=>r.category===category).length>0&&<details className="legacy-records"><summary>سجلات سابقة تحتاج تحديد الشعبة ({legacy.filter(r=>r.category===category).length})</summary><p>حُفظت هذه السجلات دون رقم مرجعي. حدّد شعبتها لتظهر ضمن إنجازك دون تكرار الشواهد.</p>{legacy.filter(r=>r.category===category).map(r=><div key={r.id}><b>{recordLabel(r)}</b><Files key={r.id} files={r.files} recordId={r.id} nextCursor={r.filesNextCursor}/><select defaultValue="" disabled={busy} aria-label={'ربط '+recordLabel(r)} onChange={e=>{const courseKey=e.target.value;if(courseKey)void action(()=>request('trainer/workspace/records/'+r.id+'/scope','PATCH',{courseKey}))}}><option value="">حدد الشعبة التابعة لهذا السجل</option>{courses.map(c=><option key={c.key} value={c.key}>{c.name} — {c.reference}</option>)}</select></div>)}</details>}
 {(!courseCategories.has(category)||course)&&<><section className="criterion-summary panel"><div><span className="eyebrow">متابعة التنفيذ</span><h3>{scope==='general'?'الإرشاد الأكاديمي العام للمدرب':course?.name}</h3>{scope!=='general'&&course&&<p>الرقم المرجعي {course.reference}</p>}<Progress label={categoryLabels[category]+': '+(scope==='general'?'عام للمدرب':course?.reference)} {...(()=>{const p=progressFor(records,scope,category);return {value:p.percent,done:p.done,total:p.total}})()}/></div><IndicatorRing value={progressFor(records,scope,category).percent} label="إنجاز المعيار" small/></section>{category==='grade_analysis'&&<CombinedGrades records={records.filter(r=>r.course_key===scope&&r.category==='grade_analysis'&&r.payload.analysisVersion===2&&r.status==='done')}/>}{category==='advising'?<div className="advising-list"><div className="list-filters"><label>عرض الممارسات<select value={advisingFilter} onChange={e=>setAdvisingFilter(e.target.value)}><option value="all">كل الممارسات</option><option value="remaining">المتبقي</option><option value="done">المنفذ</option></select></label><span>{criteria.filter(c=>c.category==='advising'&&!isComplete(saved(c),c)).length} من ١٠ ممارسات متبقية</span></div>{criteria.filter(c=>c.category==='advising'&&(advisingFilter==='all'||(advisingFilter==='done')===isComplete(saved(c),c))).map((item,i)=><details className="advising-item" key={item.key}><summary><span>{item.label}</span><span className={'tw-status '+(isComplete(saved(item),item)?'done':'not_done')}>{isComplete(saved(item),item)?'منفّذ':'لم يُنفّذ'}</span></summary>{criterionCard(item)}</details>)}</div>:<div className={'criterion-grid '+(category==='training'?'training-grid':'')}>{criteria.filter(c=>c.category===category).map(criterionCard)}</div>}</>}
 {courseCategories.has(category)&&!course&&<div className="training-preview"><div className="selection-prompt"><BookOpen/><h3>ابدأ باختيار الشعبة</h3><p>اختر المقرر ورقمه المرجعي من القائمة أعلاه. هذه قائمة البنود المطلوبة، ويُتاح توثيقها بعد الاختيار.</p></div>{criteria.filter(c=>c.category===category).map(c=><article key={c.key}><span className="module-icon"><ClipboardList/></span><h3>{c.label}</h3><p>{c.key==='methods'?'١١ أسلوبًا تدريبيًا لتوثيق ممارساتك في الشعبة.':c.key==='assignments'?'توثيق الواجبات مع شواهد التنفيذ.':'توثيق إضافي للممارسات التدريبية.'}</p><small>{c.required?'يسهم في نسبة إنجازك':'توثيق إضافي'}</small></article>)}<p className="help">اختر الشعبة من القائمة لبدء التوثيق.</p></div>}
 </>}
 {(section==='development'||section==='exchange')&&documentation()}
 {section==='assignments'&&<section className="panel"><div className="section-heading"><div><h3>التكليفات المسندة إليك</h3><p>مهام ينشئها رئيس القسم. سجّل إنجازها وأرفق ما يدعم التنفيذ.</p></div></div>{taskList()}</section>}
 {section==='alerts'&&<div className="dashboard-columns"><section className="panel"><div className="section-heading"><h3><Bell/>التنبيهات التلقائية</h3></div>{alertList()}</section><section className="panel"><div className="section-heading"><h3><CalendarDays/>أقرب المواعيد القادمة</h3></div><div className="task-list">{upcoming.map(t=><article key={t.id}><div><b>{t.title}</b><p>{date(t.due_at)}</p><small>يظهر التذكير قبل الموعد بـ {t.reminder_days} أيام.</small></div></article>)}{!upcoming.length&&<p className="empty-state">لا توجد مواعيد قادمة مسندة إليك.</p>}<Link className="text-button" href="/trainer/assignments">عرض جميع التكليفات</Link></div></section></div>}
 {section==='portfolio'&&<section className="portfolio-view panel"><div className="section-heading no-print"><div><h3>ملف الإنجاز المتكامل</h3><p>بياناتك ومؤشراتك وسجلاتك وشواهدك في ملف واحد قابل للتنزيل.</p></div><div className="action-row"><Button disabled={busy} onClick={()=>void downloadPortfolio()}><Download size={16}/>تنزيل الملف مع الشواهد</Button><Button variant="outline" disabled={busy} onClick={()=>void printSummary()}>طباعة الملخص الكامل</Button></div></div><div className="portfolio-cover"><div><p>قسم التقنية الكهربائية</p><h2>ملف الإنجاز المهني والتدريبي</h2><h3>{user.display_name}</h3><p>الرقم الوظيفي: {profile.staff_number||user.staff_number||'—'} · اسم المستخدم: {user.username}</p><p>التخصص: {profile.specialty||'لم يُحدد'} · الفصل: {term}</p></div><IndicatorRing value={score.percent}/></div><p className="help">يحتوي الملف المنزّل على جميع المرفقات الأصلية. الصور تظهر ضمن الطباعة؛ بقية الصيغ تُنزّل من داخل الملف وتُطبع عبر تطبيقاتها.</p><div className="achievement-grid">{score.categories.map(c=><div key={c.category}><h3>{categoryLabels[c.category]}</h3><Progress value={c.percent} done={c.done} total={c.total} label={c.category==='advising'?'إنجاز ممارسات الإرشاد':'متوسط إنجاز الشعب: '+categoryLabels[c.category]}/></div>)}</div><h3>ملخص المقررات والشعب</h3><CourseDataTable courses={courses} records={records} progress={data.summary?.courseProgress}/><h3>سجل المعايير والشواهد</h3>{records.map(r=><article className="portfolio-entry" key={r.id}><div><small>{categoryLabels[r.category]} · {courses.find(c=>c.key===r.course_key)?.name||'سجل المدرب'} {courses.find(c=>c.key===r.course_key)?.reference||''}</small><h4>{recordLabel(r)}</h4><p>{String(r.payload.notes||'')}</p></div><span className="tw-status">{status(r)}</span><Files key={r.id} files={r.files} recordId={r.id} nextCursor={r.filesNextCursor}/></article>)}{!records.length&&<p className="empty-state">يظهر كل سجل وشاهد هنا تلقائيًا عند توثيقه.</p>}<h3>التكليفات</h3>{taskList(false,true)}</section>}
 {data.nextCursor&&<div className="pagination-actions no-print"><span>عُرض {records.length} من {data.total} سجل</span><Button disabled={busy} variant="outline" onClick={()=>void more('records').catch(()=>{})}>عرض سجلات أخرى</Button></div>}
 {data.tasksNextCursor&&['assignments','portfolio','alerts'].includes(section)&&<div className="pagination-actions no-print"><span>عُرض {tasks.length} من {data.tasksTotal} تكليف</span><Button disabled={busy} variant="outline" onClick={()=>void more('tasks').catch(()=>{})}>عرض تكليفات أخرى</Button></div>}
 {section==='assignments'&&typeof window!=='undefined'&&new URLSearchParams(location.search).has('task')&&<a className="text-button" href="/trainer/assignments">عرض كل التكليفات</a>}
 {data.linkStatus!=='ready'&&['courses','exams','grades','blackboard','training'].includes(section)&&<p className="empty-state">{data.linkStatus==='loading'?'جارٍ تحميل الشعب…':data.linkStatus==='no_assigned_sections'?'لا توجد شعب مسندة إلى رقمك الوظيفي في تقرير الفصل الحالي.':'تعذر عرض الشعب. تحقق من اكتمال تقريري SF01 وSS01 للفصل نفسه وربط الرقم الوظيفي بالحساب.'}</p>}
 </div>;
}
function CombinedGrades({records}:{records:WorkRecord[]}){const count=records.reduce((n,r)=>n+Number(r.payload.count),0),average=count?records.reduce((n,r)=>n+Number(r.payload.averagePercent)*Number(r.payload.count),0)/count:null,pass=count?records.reduce((n,r)=>n+Number(r.payload.passed),0)*100/count:null;return <section className="combined-grades panel"><h3>المؤشر الشامل لتحليل الدرجات</h3><div className="grade-numbers"><span>الملفات المعتمدة<b>{records.length}</b></span><span>المتوسط النسبي الموزون<b>{average===null?'—':average.toFixed(1)+'٪'}</b></span><span>النجاح بين الدرجات الرقمية، موزونًا<b>{pass===null?'—':pass.toFixed(1)+'٪'}</b></span></div>{records.length>0&&<IndicatorChart title="متوسط نتائج ملفات التقييم" type="line" percent labels={records.map(r=>recordLabel(r))} series={[{label:'المتوسط النسبي',values:records.map(r=>Number(r.payload.averagePercent))}]}/>}<p className="help">تُحوّل الدرجات إلى نسبة من الدرجة العظمى لكل ملف، ثم تُوزن بعدد درجاته المعتمدة. هذا المؤشر لا يمثل المجموع النهائي لدرجات المتدرب.</p></section>}
