export type GradeSheet={name:string;rows:string[][]};
export function readCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')quoted=false;else cell+=c}else if(c==='"')quoted=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'||c==='\r'){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell=''}else cell+=c}if(quoted)throw new Error('تنسيق CSV غير مكتمل.');row.push(cell);if(row.some(Boolean))rows.push(row);return rows}
export async function readGradeWorkbook(file:File):Promise<GradeSheet[]>{
 if(file.size>10*1024*1024)throw new Error('الحد الأعلى لحجم الملف ١٠ ميغابايت.');
 if(file.name.toLowerCase().endsWith('.csv'))return [{name:'ورقة CSV',rows:readCsv((await file.text()).replace(/^\uFEFF/,''))}];
 if(!file.name.toLowerCase().endsWith('.xlsx'))throw new Error('احفظ الملف بصيغة XLSX أو CSV ثم أعد المحاولة.');
 const buffer=await file.arrayBuffer(),view=new DataView(buffer);let end=-1;
 for(let p=view.byteLength-22;p>=Math.max(0,view.byteLength-65557);p--)if(view.getUint32(p,true)===0x06054b50){end=p;break}
 if(end<0)throw new Error('تعذر قراءة بنية ملف Excel.');
 const files=new Map<string,{method:number;size:number;unpacked:number;offset:number}>();let p=view.getUint32(end+16,true),xmlSize=0;
 for(let i=0;i<view.getUint16(end+10,true);i++){if(view.getUint32(p,true)!==0x02014b50)throw new Error('بنية الملف غير صالحة.');const length=view.getUint16(p+28,true),name=new TextDecoder().decode(new Uint8Array(buffer,p+46,length));const entry={method:view.getUint16(p+10,true),size:view.getUint32(p+20,true),unpacked:view.getUint32(p+24,true),offset:view.getUint32(p+42,true)};if(/\.xml$|\.rels$/.test(name))xmlSize+=entry.unpacked;files.set(name,entry);p+=46+length+view.getUint16(p+30,true)+view.getUint16(p+32,true)}
 if(xmlSize>40*1024*1024)throw new Error('حجم أوراق العمل بعد فك الضغط يتجاوز الحد المسموح.');
 const extract=async(name:string)=>{const f=files.get(name);if(!f)return '';if(f.unpacked>20*1024*1024)throw new Error('ورقة العمل كبيرة جدًا.');const start=f.offset+30+view.getUint16(f.offset+26,true)+view.getUint16(f.offset+28,true),compressed=buffer.slice(start,start+f.size);if(f.method===0)return new TextDecoder().decode(compressed);if(f.method!==8)throw new Error('طريقة ضغط الملف غير مدعومة.');const result=await new Response(new Blob([compressed]).stream().pipeThrough(new DecompressionStream('deflate-raw'))).text();if(result.length>20*1024*1024)throw new Error('ورقة العمل كبيرة جدًا.');return result};
 const xml=(text:string)=>{const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.getElementsByTagName('parsererror').length)throw new Error('تعذر قراءة بيانات ورقة العمل.');return doc};
 const sharedText=await extract('xl/sharedStrings.xml'),shared=sharedText?Array.from(xml(sharedText).getElementsByTagName('si')).map(si=>Array.from(si.getElementsByTagName('t')).map(t=>t.textContent||'').join('')):[];
 const relationships=xml(await extract('xl/_rels/workbook.xml.rels')),paths=new Map(Array.from(relationships.getElementsByTagName('Relationship')).map(r=>[r.getAttribute('Id'),r.getAttribute('Target')||'']));
 const result:GradeSheet[]=[];
 for(const sheet of Array.from(xml(await extract('xl/workbook.xml')).getElementsByTagName('sheet'))){const target=paths.get(sheet.getAttribute('r:id'))||'',path=target.startsWith('/')?target.slice(1):'xl/'+target.replace(/^\.\//,'');if(!files.has(path))continue;const rows:string[][]=[];for(const row of Array.from(xml(await extract(path)).getElementsByTagName('row'))){const index=Number(row.getAttribute('r'))-1;if(index<0||index>20000)throw new Error('عدد صفوف الورقة يتجاوز الحد المسموح.');const values:string[]=[];for(const cell of Array.from(row.getElementsByTagName('c'))){const letters=(cell.getAttribute('r')||'A1').match(/^[A-Z]+/)?.[0]||'A';let column=0;for(const letter of letters)column=column*26+letter.charCodeAt(0)-64;if(column>500)continue;const type=cell.getAttribute('t'),v=cell.getElementsByTagName('v')[0]?.textContent;values[column-1]=type==='s'?shared[Number(v)]||'':type==='inlineStr'?cell.getElementsByTagName('is')[0]?.textContent||'':v??(cell.getElementsByTagName('f').length?'#NO_CACHED_VALUE':'')}rows[index]=values}result.push({name:sheet.getAttribute('name')||'ورقة عمل',rows})}
 if(!result.length)throw new Error('لا توجد أوراق عمل قابلة للقراءة.');return result;
}
export const gradeNumber=(text:string)=>{const v=text.trim().replace(/[٠-٩]/g,c=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(c))).replace(/٫/g,'.');return /^(?:\d+(?:\.\d*)?|\.\d+)$/.test(v)?Number(v):null};
export function gradeSuggestions(sheet:GradeSheet){const header=sheet.rows.slice(0,30).findIndex(row=>row?.some(cell=>/^(الدرجة|الدرجات|score|mark|grade)$/i.test(cell?.trim()||'')));const row=sheet.rows[header]||[];const column=row.findIndex(c=>/^(الدرجة|الدرجات|score|mark|grade)$/i.test(c?.trim()||'')),idColumn=row.findIndex(c=>/^(رقم المتدرب|الرقم التدريبي|student.?id)$/i.test(c?.trim()||''));let maximum=100;for(const r of sheet.rows.slice(0,Math.max(header,1))){const i=r?.findIndex(v=>v?.includes('الدرجة العظمى'));if(i!==undefined&&i>=0){const n=gradeNumber(r[i+1]||'');if(n&&n<=100)maximum=n}}
 let last=header+1;for(let i=header+1;i<sheet.rows.length;i++){const v=sheet.rows[i]?.[idColumn>=0?idColumn:column]||'';if(gradeNumber(v)!==null)last=i+1;else if(last>header+1)break}
 const term=sheet.rows.slice(0,4).flat().find(v=>/^14\d{4}$/.test(v?.trim()||''));return {header:Math.max(1,header+1),column,idColumn,firstRow:Math.max(2,header+2),lastRow:Math.max(header+2,last),maximum,term};
}
export function selectedGrades(sheet:GradeSheet,column:number,first:number,last:number,maximum:number){if(column<0||first<1||last<first||last-first>2000)throw new Error('حدد عمود الدرجات ونطاق صفوف المتدربين.');const scores:number[]=[];let excluded=0;const invalid:number[]=[];for(let i=first-1;i<last;i++){const text=(sheet.rows[i]?.[column]||'').trim();if(!text||['غائب','غ','محروم','منسحب','مطوي قيده','—','-'].includes(text)){excluded++;continue}const value=gradeNumber(text);if(value===null||value>maximum||value>100)invalid.push(i+1);else scores.push(value)}if(invalid.length)throw new Error('راجع الدرجات في الصفوف: '+invalid.slice(0,12).join('، ')+'. لا تُقبل نصوص أو درجات تتجاوز الدرجة العظمى.');if(!scores.length)throw new Error('لا توجد درجات رقمية في النطاق المختار.');return {scores,excluded}}
