export type WorkFile={id:string;original_filename:string;content_type?:string;byte_size:number;created_at:number;purpose?:'evidence'|'decision'};
export type WorkRecord={id:string;course_key:string;category:string;item_key:string;status:'done'|'not_done'|'not_applicable';payload:Record<string,unknown>;updated_at:number;files:WorkFile[]};
export type TrainerCourse={key:string;name:string;code:string;reference:string;term:string;sectionType:string;sections:number;trainees:number;deprived:number;withdrawn:number;dismissed:number;learnerIds:string[]};
export type TrainerTask={id:string;trainer_id:string;trainer_name?:string;title:string;description:string;due_at:string;reminder_days:number;status:'pending'|'done';created_by:string;created_by_name?:string;updated_at:number};
export type Criterion={category:string;key:string;label:string;required:boolean;witness:boolean};
export const trainingMethods=['التطبيق العملي','المشروع','طريقة K.W.L','التدريب بالاكتشاف','التدريب البنائي','نظرية (TRIZ)','حل المشكلات','التدريب المعكوس','التدريب بالمحاكاة','دراسة الحالة','التدريب المتمايز'];
export const criteria:Criterion[]=[
 ...[['methods','أساليب التدريب'],['assignments','الواجبات'],['projects','المشاريع'],['research','البحوث']].map(([key,label])=>({category:'training',key,label,required:['methods','assignments'].includes(key),witness:key==='assignments'})),
 ...[['first','نسخة الاختبار الفصلي الأول'],['second','نسخة الاختبار الفصلي الثاني'],['final','نسخة الاختبار النهائي']].map(([key,label])=>({category:'exam',key,label,required:true,witness:true})),
 ...[['mid1','تحليل درجات الاختبار الفصلي الأول'],['mid2','تحليل درجات الاختبار الفصلي الثاني'],['final','تحليل درجات الاختبار النهائي'],['participation','تحليل درجات المشاركة']].map(([key,label])=>({category:'grade_analysis',key,label,required:key!=='participation',witness:true})),
 ...[['content','شاهد إتاحة المحتوى التدريبي على Blackboard'],['syllabus','شاهد رفع ملف المدرب وتوصيف المقرر على Blackboard'],['optional-0','المهارات العملية'],['optional-1','الاختبارات الإلكترونية'],['optional-2','الواجبات الإلكترونية']].map(([key,label])=>({category:'blackboard',key,label,required:!key.startsWith('optional'),witness:!key.startsWith('optional')})),
 ...['تقديم المعلومات الإرشادية والتدريبية','توضيح دور المرشد التدريبي','التعريف بالخطة التدريبية','أهمية الحضور وأثر الغياب','المتابعة المستمرة للمتدرب','الاجتماع الفردي','المتابعة المبكرة للمتعثرين','تحفيز المتدربين المتميزين','قائمة المنذرين والمحرومين','التنسيق مع وحدة التوجيه والإرشاد'].map((label,i)=>({category:'advising',key:'a'+i,label,required:true,witness:false}))
];
export const categoryLabels:Record<string,string>={exam:'الاختبارات',grade_analysis:'تحليل الدرجات',blackboard:'التدرّب الإلكتروني',advising:'الإرشاد الأكاديمي',development:'التطور المهني',assignment:'التكليفات',exchange:'تبادل الخبرات',schedule:'المواعيد السابقة',initiative:'المبادرات والمساهمات',training:'المهام التدريبية',portfolio:'ملف الإنجاز'};
export const courseCategories=new Set(['exam','grade_analysis','blackboard','training']);
export function recordLabel(r:Pick<WorkRecord,'category'|'item_key'|'payload'>){return String(r.payload.title||criteria.find(c=>c.category===r.category&&c.key===r.item_key)?.label||categoryLabels[r.category]||'سجل موثق')}
export function isComplete(record:WorkRecord|undefined,item:Criterion){return !!record&&record.status==='done'&&(!item.witness||record.files.length>0)&&(item.category!=='training'||item.key!=='methods'||Array.isArray(record.payload.methods)&&record.payload.methods.length>0)&&(item.category!=='grade_analysis'||record.payload.analysisVersion===2)}
export function progressFor(records:WorkRecord[],key:string,category?:string){const items=criteria.filter(c=>c.required&&(!category||c.category===category)&&(key==='general'?c.category==='advising':courseCategories.has(c.category)));let done=0,total=0;for(const item of items){const r=records.find(r=>r.course_key===key&&r.category===item.category&&r.item_key===item.key);if(r?.status==='not_applicable')continue;total++;if(isComplete(r,item))done++}return {done,total,percent:total?Math.round(done*100/total):null}}
export function trainerProgress(records:WorkRecord[],courses:TrainerCourse[]){const categories=['exam','grade_analysis','blackboard','training','advising'];const values=categories.map(category=>{const values=category==='advising'?[progressFor(records,'general',category)]:courses.map(c=>progressFor(records,c.key,category));const applicable=values.filter(p=>p.percent!==null);return {category,done:values.reduce((n,v)=>n+v.done,0),total:values.reduce((n,v)=>n+v.total,0),percent:applicable.length?Math.round(applicable.reduce((n,v)=>n+(v.percent||0),0)/applicable.length):null}});const active=values.filter(v=>v.percent!==null);return {categories:values,percent:active.length?Math.round(active.reduce((n,v)=>n+(v.percent||0),0)/active.length):null}}
export function taskAlerts(tasks:TrainerTask[],now=Date.now()){return tasks.filter(t=>t.status!=='done'&&Date.parse(t.due_at)-now<=t.reminder_days*86400000).map(t=>({...t,overdue:Date.parse(t.due_at)<now})).sort((a,b)=>Date.parse(a.due_at)-Date.parse(b.due_at))}
export type GradeInput={scores:number[];maximum:number;passMark:number;sheet:string;column:string;firstRow:number;lastRow:number;excluded:number};
export function calculateGrades(input:GradeInput){const {scores,maximum,passMark}=input;if(!scores.length||scores.length>2000)throw new Error('حدد نطاقًا يحتوي على درجات فعلية وبحد أقصى ٢٠٠٠ درجة.');if(!Number.isFinite(maximum)||maximum<=0||maximum>100||!Number.isFinite(passMark)||passMark<0||passMark>maximum)throw new Error('تحقق من الدرجة العظمى وحد النجاح؛ الدرجة العظمى لا تتجاوز ١٠٠.');if(scores.some(v=>!Number.isFinite(v)||v<0||v>maximum))throw new Error('توجد درجات خارج النطاق المحدد. راجع عمود الدرجات ونطاق الصفوف.');const average=scores.reduce((a,b)=>a+b,0)/scores.length,passed=scores.filter(v=>v>=passMark).length;const distribution=[{label:'٩٠–١٠٠٪',min:90,max:101},{label:'٨٠–أقل من ٩٠٪',min:80,max:90},{label:'٧٠–أقل من ٨٠٪',min:70,max:80},{label:'٦٠–أقل من ٧٠٪',min:60,max:70},{label:'أقل من ٦٠٪',min:0,max:60}].map(b=>({...b,count:scores.filter(v=>v*100/maximum>=b.min&&v*100/maximum<b.max).length}));const passRate=passed*100/scores.length;return {...input,analysisVersion:2,count:scores.length,average:+average.toFixed(2),averagePercent:+(average*100/maximum).toFixed(2),max:Math.max(...scores),min:Math.min(...scores),passed,passRate:+passRate.toFixed(2),distribution,recommendations:passRate<70?['مراجعة المهارات التي تركز فيها التعثر، وإعداد أنشطة علاجية قصيرة.','تنفيذ تقييم تكويني بعد الدعم لقياس تحسن الإتقان.']:['مراجعة الأسئلة الأكثر صعوبة وتقديم تغذية راجعة فردية.','تقديم أنشطة إثرائية للمتدربين المتقنين.']};}
